/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-02-06 04:58:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hospital;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class animal_005fhospital_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/hospital/../includes/header.jsp", Long.valueOf(1675659477208L));
    _jspx_dependants.put("/WEB-INF/views/hospital/../includes/footer.jsp", Long.valueOf(1675659477205L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673112267838L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <title>애니모어 유기동물 보호센터</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write(" \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/animate.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap-datepicker.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/flaticon.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\n");
      out.write("    <link href=\"https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/anymore.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://kit.fontawesome.com/c27a828741.css\" crossorigin=\"anonymous\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("  \n");
      out.write("  <div class=\"wrap\" >\n");
      out.write("			<div class=\"container\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("				   	<div class=\"col-md-4\">	\n");
      out.write("						<div class=\"social-media\">\n");
      out.write("				    		<p class=\"mb-0 d-flex\">\n");
      out.write("				    			<a href=\"https://www.facebook.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-facebook\"><i class=\"sr-only\">Facebook</i></span></a>\n");
      out.write("				    			<a href=\"https://twitter.com/?lang=ko\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-twitter\"><i class=\"sr-only\">Twitter</i></span></a>\n");
      out.write("				    			<a href=\"https://www.instagram.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-instagram\"><i class=\"sr-only\">Instagram</i></span></a>\n");
      out.write("				    		</p>\n");
      out.write("		        		</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("			          <div class=\"col-md-8 d-flex align-items-center justify-content-end\">\n");
      out.write("			            <div class=\"social-media\">\n");
      out.write("				              <p class=\"mb-0 phone pl-md-2\">\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				              </p>\n");
      out.write("			            </div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("		\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\n");
      out.write("	    <div class=\"container\" >\n");
      out.write("	    	<a class=\"navbar-brand\" href=\"/index\"><span class=\"flaticon-pawprint-1 mr-2\"></span>Anymore</a>\n");
      out.write("	      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("	        <span class=\"fa fa-bars\"></span> Menu\n");
      out.write("	      </button>\n");
      out.write("	      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\" style=\"font-family: 'NanumSquareNeo';\">\n");
      out.write("	        <ul class=\"navbar-nav ml-auto\">\n");
      out.write("	        	<li id=\"home\" class=\"nav-item active\"><a href=\"/index\" class=\"nav-link\">HOME</a></li>\n");
      out.write("            <li id=\"about\" class=\"nav-item dropdown\"><a href=\"/about/introduce\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">보호소 소개</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/about/introduce\" class=\"dropdown-item\">소개</a>\n");
      out.write("                <a href=\"/about/map\" class=\"dropdown-item\">찾아오시는 길</a>\n");
      out.write("                <a href=\"/about/support\" class=\"dropdown-item\">후원</a>\n");
      out.write("                <a href=\"/about/facility\" class=\"dropdown-item\">보호소 시설 안내</a>\n");
      out.write("              </div>\n");
      out.write("            <li id=\"adopt\" class=\"nav-item dropdown\"><a href=\"/adopt/procedure\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입양하기</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/adopt/procedure\" class=\"dropdown-item\">입양절차</a>\n");
      out.write("                <a href=\"/adopt/protectAnimal\" class=\"dropdown-item\">입양하기</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">실종신고</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾습니다</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾았습니다</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("<!-- 	        <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입소신청</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소신청</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소절차</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("            \n");
      out.write("	          <li id=\"community\" class=\"nav-item dropdown\"><a href=\"/community/adoptionReview\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">커뮤니티</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/community/adoptionReview\" class=\"dropdown-item\">입양후기</a>\n");
      out.write("              	<a href=\"/community/freeBoard\" class=\"dropdown-item\">자유게시판</a>\n");
      out.write("                <!-- <a href=\"#\" class=\"dropdown-item\">진행중인 캠페인</a> -->\n");
      out.write("                <a href=\"/community/usedItems\" class=\"dropdown-item\">중고거래게시판</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">중고거래</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">채팅목록</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래 후기</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("\n");
      out.write("            <li id=\"reservation\" class=\"nav-item dropdown\"><a href=\"/reservation/visit\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">방문예약</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/reservation/visit\" class=\"dropdown-item\">방문상담 예약</a>\n");
      out.write("                <a href=\"/reservation/volunteer\" class=\"dropdown-item\">봉사활동 예약</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            \n");
      out.write("            <li id=\"mall\" class=\"nav-item dropdown\"><a href=\"/anymoremall/product_list\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">애니모어 몰</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/anymoremall/product_list\" class=\"dropdown-item\">상품목록</a>\n");
      out.write("                <a href=\"/anymoremall/cart\" class=\"dropdown-item\">장바구니</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("	        </ul>\n");
      out.write("	      </div>\n");
      out.write("	    </div>\n");
      out.write("	  </nav>\n");
      out.write("	  \n");
      out.write("	  <!-- loader -->\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"../js/jquery.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\n");
      out.write("  <script src=\"../js/main.js\"></script>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* 	.hos_map img{ */\r\n");
      out.write("/* 		position:relative; */\r\n");
      out.write("/* 		right:30px; */\r\n");
      out.write("/* 		width: 1200px; */\r\n");
      out.write("/* 		text-align:center; */\r\n");
      out.write("/* 		padding:50px; */\r\n");
      out.write("/* 	} */\r\n");
      out.write("	\r\n");
      out.write("/* 	.hos_list{ */\r\n");
      out.write("/* 		font-family:NanumSquareNeo; */\r\n");
      out.write("/* 		text-align:center; */\r\n");
      out.write("/* 		padding:20px; */\r\n");
      out.write("/* 	} */\r\n");
      out.write("	\r\n");
      out.write("	.map_wrap, .map_wrap * {margin:0;padding:0;font-size:12px;font-family:NanumSquareNeo;color:black;font-weight:500;}\r\n");
      out.write("	.map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}\r\n");
      out.write("	.map_wrap {position:relative;margin:auto;display:block;width:1070px;height:600px;margin-top:30px;margin-bottom:50px;font-family:NanumSquareNeo;}\r\n");
      out.write("	#menu_wrap {position:absolute;top:0;left:0;bottom:0;width:300px;margin:10px 0 30px 10px;padding:5px;overflow-y:auto;background:rgba(255, 255, 255, 0.9);z-index: 1;font-size:12px;border-radius: 10px;}\r\n");
      out.write("	.bg_white {background:#fff;}\r\n");
      out.write("	#menu_wrap hr {display: block; height: 1px;border: 0; border-top: 2px solid #5F5F5F;margin:3px 0;}\r\n");
      out.write("	#menu_wrap .option{text-align: center;}\r\n");
      out.write("	#menu_wrap .option p {margin:10px 0;}  \r\n");
      out.write("	#menu_wrap .option button {margin-left:5px;}\r\n");
      out.write("	#placesList li {list-style: none;}\r\n");
      out.write("	#placesList .item {position:relative;border-bottom:1px solid #888;overflow: hidden;cursor: pointer;min-height: 65px;}\r\n");
      out.write("	#placesList .item span {display: block;margin-top:4px;}\r\n");
      out.write("	#placesList .item h5, #placesList .item .info {text-overflow: ellipsis;overflow: hidden;white-space: nowrap;font-family:NanumSquareNeo;color:black;font-weight:600;}\r\n");
      out.write("	#placesList .item .info{padding:10px 0 10px 55px;}\r\n");
      out.write("	#placesList .info .gray {color:#8a8a8a;}\r\n");
      out.write("	#placesList .info .jibun {padding-left:26px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_jibun.png) no-repeat;}\r\n");
      out.write("	#placesList .info .tel {color:#009900;}\r\n");
      out.write("	#placesList .item .markerbg {float:left;position:absolute;width:36px; height:37px;margin:10px 0 0 10px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png) no-repeat;}\r\n");
      out.write("	#placesList .item .marker_1 {background-position: 0 -10px;}\r\n");
      out.write("	#placesList .item .marker_2 {background-position: 0 -56px;}\r\n");
      out.write("	#placesList .item .marker_3 {background-position: 0 -102px}\r\n");
      out.write("	#placesList .item .marker_4 {background-position: 0 -148px;}\r\n");
      out.write("	#placesList .item .marker_5 {background-position: 0 -194px;}\r\n");
      out.write("	#placesList .item .marker_6 {background-position: 0 -240px;}\r\n");
      out.write("	#placesList .item .marker_7 {background-position: 0 -286px;}\r\n");
      out.write("	#placesList .item .marker_8 {background-position: 0 -332px;}\r\n");
      out.write("	#placesList .item .marker_9 {background-position: 0 -378px;}\r\n");
      out.write("	#placesList .item .marker_10 {background-position: 0 -423px;}\r\n");
      out.write("	#placesList .item .marker_11 {background-position: 0 -470px;}\r\n");
      out.write("	#placesList .item .marker_12 {background-position: 0 -516px;}\r\n");
      out.write("	#placesList .item .marker_13 {background-position: 0 -562px;}\r\n");
      out.write("	#placesList .item .marker_14 {background-position: 0 -608px;}\r\n");
      out.write("	#placesList .item .marker_15 {background-position: 0 -654px;}\r\n");
      out.write("	#pagination {margin:10px auto;text-align: center;}\r\n");
      out.write("	#pagination a {display:inline-block;margin-right:10px;}\r\n");
      out.write("	#pagination .on {font-weight: bold; cursor: default;color:#777;}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"hero-wrap hero-wrap-2\"\r\n");
      out.write("	style=\"background-image: url('../images/cat-bg.jpg');\"\r\n");
      out.write("	data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("	<div class=\"overlay\"></div>\r\n");
      out.write("	<div class=\"container\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("		<div class=\"row no-gutters slider-text align-items-end\">\r\n");
      out.write("			<div class=\"col-md-9 ftco-animate pb-5\">\r\n");
      out.write("				<h1 class=\"mb-0 bread\" style=\"font-family: 'NanumSquareNeo';\">동물병원 검색</h1>\r\n");
      out.write("				<p class=\"breadcrumbs mb-2\" style=\"padding:10px;\">\r\n");
      out.write("					<span class=\"mr-2\" style=\"color: gray;\">동물병원 검색</span>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write(" \r\n");
      out.write("<div class=\"title\">\r\n");
      out.write("	<h1>동물병원 검색</h1><br />\r\n");
      out.write("	가까운 동물병원을 찾아보세요.\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- hospital map -->\r\n");
      out.write("<!-- <div class=\"container\"> -->\r\n");
      out.write("<!-- 	<div class=\"row\"> -->\r\n");
      out.write("<!-- 		<div class=\"map\" id=\"map\"> -->\r\n");
      out.write("		\r\n");
      out.write("<!-- 		</div> -->\r\n");
      out.write("<!-- 	</div> -->\r\n");
      out.write("	\r\n");
      out.write("<!-- 	<div class=\"hos_list\"> -->\r\n");
      out.write("<!--         <table class=\"table table-hover\"> -->\r\n");
      out.write("<!--             <tr class=\"index table-active\"> -->\r\n");
      out.write("<!--                 <td>병원명</td> -->\r\n");
      out.write("<!--                 <td>위 치</td> -->\r\n");
      out.write("<!--             </tr> -->\r\n");
      out.write("\r\n");
      out.write("<!--             <tr> -->\r\n");
      out.write("<!--                 <td>이든 동물의료센터</td> -->\r\n");
      out.write("<!--                 <td>서울 영등포구 양평로 5 성원빌딩</td> -->\r\n");
      out.write("<!--             </tr> -->\r\n");
      out.write("<!--             <tr> -->\r\n");
      out.write("<!--                 <td>미소로 동물병원</td> -->\r\n");
      out.write("<!--                 <td>서울 영등포구 영신로 238 미소로</td> -->\r\n");
      out.write("<!--             </tr> -->\r\n");
      out.write("<!--             <tr> -->\r\n");
      out.write("<!--                 <td>영등포 아크로 동물병원</td> -->\r\n");
      out.write("<!--                 <td>서울 영등포구 국회대로54길 10 아크로타워스퀘어 근린생활시설 6동 2호</td> -->\r\n");
      out.write("<!--             </tr> -->\r\n");
      out.write("<!--         </table> -->\r\n");
      out.write("<!-- 	</div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"map_wrap container\" style=\"margin-bottom: 200px\">\r\n");
      out.write("    <div id=\"map\" style=\"width:100%;height:100%;position:relative;overflow:hidden;\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"menu_wrap\" class=\"bg_white\">\r\n");
      out.write("        <div class=\"option\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <form onsubmit=\"searchPlaces(); return false;\">\r\n");
      out.write("                    키워드 : <input type=\"text\" value=\"성동구 동물 병원\" id=\"keyword\" size=\"15\"> \r\n");
      out.write("                    <input type=\"submit\" value=\"검색하기\"> \r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <ul id=\"placesList\"></ul>\r\n");
      out.write("        <div id=\"pagination\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=56efd6c06fb480c58b736f058c3d17a4&libraries=services&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// 마커를 담을 배열입니다\r\n");
      out.write("var markers = [];\r\n");
      out.write("\r\n");
      out.write("var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = {\r\n");
      out.write("        center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표\r\n");
      out.write("        level: 3 // 지도의 확대 레벨\r\n");
      out.write("    };  \r\n");
      out.write("\r\n");
      out.write("// 지도를 생성합니다    \r\n");
      out.write("var map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("\r\n");
      out.write("// 장소 검색 객체를 생성합니다\r\n");
      out.write("var ps = new kakao.maps.services.Places();  \r\n");
      out.write("\r\n");
      out.write("// 검색 결과 목록이나 마커를 클릭했을 때 장소명을 표출할 인포윈도우를 생성합니다\r\n");
      out.write("var infowindow = new kakao.maps.InfoWindow({zIndex:1});\r\n");
      out.write("\r\n");
      out.write("// 키워드로 장소를 검색합니다\r\n");
      out.write("searchPlaces();\r\n");
      out.write("\r\n");
      out.write("// 키워드 검색을 요청하는 함수입니다\r\n");
      out.write("function searchPlaces() {\r\n");
      out.write("\r\n");
      out.write("    var keyword = document.getElementById('keyword').value;\r\n");
      out.write("\r\n");
      out.write("    if (!keyword.replace(/^\\s+|\\s+$/g, '')) {\r\n");
      out.write("        alert('키워드를 입력해주세요!');\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 장소검색 객체를 통해 키워드로 장소검색을 요청합니다\r\n");
      out.write("    ps.keywordSearch( keyword, placesSearchCB); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 장소검색이 완료됐을 때 호출되는 콜백함수 입니다\r\n");
      out.write("function placesSearchCB(data, status, pagination) {\r\n");
      out.write("    if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("        // 정상적으로 검색이 완료됐으면\r\n");
      out.write("        // 검색 목록과 마커를 표출합니다\r\n");
      out.write("        displayPlaces(data);\r\n");
      out.write("\r\n");
      out.write("        // 페이지 번호를 표출합니다\r\n");
      out.write("        displayPagination(pagination);\r\n");
      out.write("\r\n");
      out.write("    } else if (status === kakao.maps.services.Status.ZERO_RESULT) {\r\n");
      out.write("\r\n");
      out.write("        alert('검색 결과가 존재하지 않습니다.');\r\n");
      out.write("        return;\r\n");
      out.write("\r\n");
      out.write("    } else if (status === kakao.maps.services.Status.ERROR) {\r\n");
      out.write("\r\n");
      out.write("        alert('검색 결과 중 오류가 발생했습니다.');\r\n");
      out.write("        return;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색 결과 목록과 마커를 표출하는 함수입니다\r\n");
      out.write("function displayPlaces(places) {\r\n");
      out.write("\r\n");
      out.write("    var listEl = document.getElementById('placesList'), \r\n");
      out.write("    menuEl = document.getElementById('menu_wrap'),\r\n");
      out.write("    fragment = document.createDocumentFragment(), \r\n");
      out.write("    bounds = new kakao.maps.LatLngBounds(), \r\n");
      out.write("    listStr = '';\r\n");
      out.write("    \r\n");
      out.write("    // 검색 결과 목록에 추가된 항목들을 제거합니다\r\n");
      out.write("    removeAllChildNods(listEl);\r\n");
      out.write("\r\n");
      out.write("    // 지도에 표시되고 있는 마커를 제거합니다\r\n");
      out.write("    removeMarker();\r\n");
      out.write("    \r\n");
      out.write("    for ( var i=0; i<places.length; i++ ) {\r\n");
      out.write("\r\n");
      out.write("        // 마커를 생성하고 지도에 표시합니다\r\n");
      out.write("        var placePosition = new kakao.maps.LatLng(places[i].y, places[i].x),\r\n");
      out.write("            marker = addMarker(placePosition, i), \r\n");
      out.write("            itemEl = getListItem(i, places[i]); // 검색 결과 항목 Element를 생성합니다\r\n");
      out.write("\r\n");
      out.write("        // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해\r\n");
      out.write("        // LatLngBounds 객체에 좌표를 추가합니다\r\n");
      out.write("        bounds.extend(placePosition);\r\n");
      out.write("\r\n");
      out.write("        // 마커와 검색결과 항목에 mouseover 했을때\r\n");
      out.write("        // 해당 장소에 인포윈도우에 장소명을 표시합니다\r\n");
      out.write("        // mouseout 했을 때는 인포윈도우를 닫습니다\r\n");
      out.write("        (function(marker, title) {\r\n");
      out.write("            kakao.maps.event.addListener(marker, 'mouseover', function() {\r\n");
      out.write("                displayInfowindow(marker, title);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            kakao.maps.event.addListener(marker, 'mouseout', function() {\r\n");
      out.write("                infowindow.close();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            itemEl.onmouseover =  function () {\r\n");
      out.write("                displayInfowindow(marker, title);\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            itemEl.onmouseout =  function () {\r\n");
      out.write("                infowindow.close();\r\n");
      out.write("            };\r\n");
      out.write("        })(marker, places[i].place_name);\r\n");
      out.write("\r\n");
      out.write("        fragment.appendChild(itemEl);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 검색결과 항목들을 검색결과 목록 Element에 추가합니다\r\n");
      out.write("    listEl.appendChild(fragment);\r\n");
      out.write("    menuEl.scrollTop = 0;\r\n");
      out.write("\r\n");
      out.write("    // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다\r\n");
      out.write("    map.setBounds(bounds);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색결과 항목을 Element로 반환하는 함수입니다\r\n");
      out.write("function getListItem(index, places) {\r\n");
      out.write("\r\n");
      out.write("    var el = document.createElement('li'),\r\n");
      out.write("    itemStr = '<span class=\"markerbg marker_' + (index+1) + '\"></span>' +\r\n");
      out.write("                '<div class=\"info\">' +\r\n");
      out.write("                '   <h5>' + places.place_name + '</h5>';\r\n");
      out.write("\r\n");
      out.write("    if (places.road_address_name) {\r\n");
      out.write("        itemStr += '    <span>' + places.road_address_name + '</span>' +\r\n");
      out.write("                    '   <span class=\"jibun gray\">' +  places.address_name  + '</span>';\r\n");
      out.write("    } else {\r\n");
      out.write("        itemStr += '    <span>' +  places.address_name  + '</span>'; \r\n");
      out.write("    }\r\n");
      out.write("                 \r\n");
      out.write("      itemStr += '  <span class=\"tel\">' + places.phone  + '</span>' +\r\n");
      out.write("                '</div>';           \r\n");
      out.write("\r\n");
      out.write("    el.innerHTML = itemStr;\r\n");
      out.write("    el.className = 'item';\r\n");
      out.write("\r\n");
      out.write("    return el;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 마커를 생성하고 지도 위에 마커를 표시하는 함수입니다\r\n");
      out.write("function addMarker(position, idx, title) {\r\n");
      out.write("    var imageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png', // 마커 이미지 url, 스프라이트 이미지를 씁니다\r\n");
      out.write("        imageSize = new kakao.maps.Size(36, 37),  // 마커 이미지의 크기\r\n");
      out.write("        imgOptions =  {\r\n");
      out.write("            spriteSize : new kakao.maps.Size(36, 691), // 스프라이트 이미지의 크기\r\n");
      out.write("            spriteOrigin : new kakao.maps.Point(0, (idx*46)+10), // 스프라이트 이미지 중 사용할 영역의 좌상단 좌표\r\n");
      out.write("            offset: new kakao.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표\r\n");
      out.write("        },\r\n");
      out.write("        markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imgOptions),\r\n");
      out.write("            marker = new kakao.maps.Marker({\r\n");
      out.write("            position: position, // 마커의 위치\r\n");
      out.write("            image: markerImage \r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    marker.setMap(map); // 지도 위에 마커를 표출합니다\r\n");
      out.write("    markers.push(marker);  // 배열에 생성된 마커를 추가합니다\r\n");
      out.write("\r\n");
      out.write("    return marker;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 지도 위에 표시되고 있는 마커를 모두 제거합니다\r\n");
      out.write("function removeMarker() {\r\n");
      out.write("    for ( var i = 0; i < markers.length; i++ ) {\r\n");
      out.write("        markers[i].setMap(null);\r\n");
      out.write("    }   \r\n");
      out.write("    markers = [];\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색결과 목록 하단에 페이지번호를 표시는 함수입니다\r\n");
      out.write("function displayPagination(pagination) {\r\n");
      out.write("    var paginationEl = document.getElementById('pagination'),\r\n");
      out.write("        fragment = document.createDocumentFragment(),\r\n");
      out.write("        i; \r\n");
      out.write("\r\n");
      out.write("    // 기존에 추가된 페이지번호를 삭제합니다\r\n");
      out.write("    while (paginationEl.hasChildNodes()) {\r\n");
      out.write("        paginationEl.removeChild (paginationEl.lastChild);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    for (i=1; i<=pagination.last; i++) {\r\n");
      out.write("        var el = document.createElement('a');\r\n");
      out.write("        el.href = \"#\";\r\n");
      out.write("        el.innerHTML = i;\r\n");
      out.write("\r\n");
      out.write("        if (i===pagination.current) {\r\n");
      out.write("            el.className = 'on';\r\n");
      out.write("        } else {\r\n");
      out.write("            el.onclick = (function(i) {\r\n");
      out.write("                return function() {\r\n");
      out.write("                    pagination.gotoPage(i);\r\n");
      out.write("                }\r\n");
      out.write("            })(i);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        fragment.appendChild(el);\r\n");
      out.write("    }\r\n");
      out.write("    paginationEl.appendChild(fragment);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 검색결과 목록 또는 마커를 클릭했을 때 호출되는 함수입니다\r\n");
      out.write("// 인포윈도우에 장소명을 표시합니다\r\n");
      out.write("function displayInfowindow(marker, title) {\r\n");
      out.write("    var content = '<div style=\"padding:5px;z-index:1;\">' + title + '</div>';\r\n");
      out.write("\r\n");
      out.write("    infowindow.setContent(content);\r\n");
      out.write("    infowindow.open(map, marker);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" // 검색결과 목록의 자식 Element를 제거하는 함수입니다\r\n");
      out.write("function removeAllChildNods(el) {   \r\n");
      out.write("    while (el.hasChildNodes()) {\r\n");
      out.write("        el.removeChild (el.lastChild);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"> \r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"footer\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Anymore</h2>\r\n");
      out.write("						<p>우리 미래 세대에게 진정한 가치 사회를 이어주고 동물들이 웃을 수 있는 사회가 되기 위해 애니모어가 최선의 노력을 하겠습니다. 애니모어에 지속적인 관심과 격려로 함께 해주세요.</p>\r\n");
      out.write("						<br/>\r\n");
      out.write("			<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.facebook.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Facebook\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://twitter.com/?lang=ko\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Twitter\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.instagram.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Instagram\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Have a Questions?</h2>\r\n");
      out.write("						<div class=\"block-23 mb-3\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><span class=\"icon fa fa-map\"></span><span class=\"text\">서울특별시 성동구 행당로 17길 1-77</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-phone\"></span><span class=\"text\">02-2292-6337<br>(평일 09:00~12:00, 13:00~18:00)</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-paper-plane\"></span><span class=\"text\">info@anymore.or.kr</span></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("					</div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">후원문의</h2>\r\n");
      out.write("						<p>후원금은 사지 않고 입양하는 문화를 만들어 가기 위한 활동에 사용됩니다.</p>\r\n");
      out.write("            <a href=\"/about/support\">바로가기</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row mt-5\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib.com</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/hospital/../includes/header.jsp(51,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 전 -->\n");
          out.write("					                <a href=\"/member/login\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Login</span></a>\n");
          out.write("					                <a href=\"/join/join_main\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> Join</span></a>\n");
          out.write("					                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/hospital/../includes/header.jsp(56,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 후 -->\n");
          out.write("					                ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("			                        ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/hospital/../includes/header.jsp(57,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 관리자 로그인 -->\n");
          out.write("			                          ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write(" 관리자님 께서 로그인 중입니다.&nbsp;\n");
          out.write("			                          <a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						               <a href=\"/staffMyPage/member_list\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						               <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("			                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/hospital/../includes/header.jsp(58,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/hospital/../includes/header.jsp(63,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'n'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 사용자 로그인 -->\n");
          out.write("			                        	");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write(" 님께서 로그인 중입니다.&nbsp;\n");
          out.write("						              	<a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						                <a href=\"/myPage/edit\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/hospital/../includes/header.jsp(64,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
