/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-02-08 03:13:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/join/../includes/footer.jsp", Long.valueOf(1675659477205L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673112267838L));
    _jspx_dependants.put("/WEB-INF/views/join/../includes/header.jsp", Long.valueOf(1675659477208L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <title>애니모어 유기동물 보호센터</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write(" \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/animate.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap-datepicker.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/flaticon.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\n");
      out.write("    <link href=\"https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/anymore.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://kit.fontawesome.com/c27a828741.css\" crossorigin=\"anonymous\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("  \n");
      out.write("  <div class=\"wrap\" >\n");
      out.write("			<div class=\"container\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("				   	<div class=\"col-md-4\">	\n");
      out.write("						<div class=\"social-media\">\n");
      out.write("				    		<p class=\"mb-0 d-flex\">\n");
      out.write("				    			<a href=\"https://www.facebook.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-facebook\"><i class=\"sr-only\">Facebook</i></span></a>\n");
      out.write("				    			<a href=\"https://twitter.com/?lang=ko\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-twitter\"><i class=\"sr-only\">Twitter</i></span></a>\n");
      out.write("				    			<a href=\"https://www.instagram.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-instagram\"><i class=\"sr-only\">Instagram</i></span></a>\n");
      out.write("				    		</p>\n");
      out.write("		        		</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("			          <div class=\"col-md-8 d-flex align-items-center justify-content-end\">\n");
      out.write("			            <div class=\"social-media\">\n");
      out.write("				              <p class=\"mb-0 phone pl-md-2\">\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				              </p>\n");
      out.write("			            </div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("		\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\n");
      out.write("	    <div class=\"container\" >\n");
      out.write("	    	<a class=\"navbar-brand\" href=\"/index\"><span class=\"flaticon-pawprint-1 mr-2\"></span>Anymore</a>\n");
      out.write("	      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("	        <span class=\"fa fa-bars\"></span> Menu\n");
      out.write("	      </button>\n");
      out.write("	      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\" style=\"font-family: 'NanumSquareNeo';\">\n");
      out.write("	        <ul class=\"navbar-nav ml-auto\">\n");
      out.write("	        	<li id=\"home\" class=\"nav-item active\"><a href=\"/index\" class=\"nav-link\">HOME</a></li>\n");
      out.write("            <li id=\"about\" class=\"nav-item dropdown\"><a href=\"/about/introduce\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">보호소 소개</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/about/introduce\" class=\"dropdown-item\">소개</a>\n");
      out.write("                <a href=\"/about/map\" class=\"dropdown-item\">찾아오시는 길</a>\n");
      out.write("                <a href=\"/about/support\" class=\"dropdown-item\">후원</a>\n");
      out.write("                <a href=\"/about/facility\" class=\"dropdown-item\">보호소 시설 안내</a>\n");
      out.write("              </div>\n");
      out.write("            <li id=\"adopt\" class=\"nav-item dropdown\"><a href=\"/adopt/procedure\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입양하기</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/adopt/procedure\" class=\"dropdown-item\">입양절차</a>\n");
      out.write("                <a href=\"/adopt/protectAnimal\" class=\"dropdown-item\">입양하기</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">실종신고</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾습니다</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾았습니다</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("<!-- 	        <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입소신청</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소신청</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소절차</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("            \n");
      out.write("	          <li id=\"community\" class=\"nav-item dropdown\"><a href=\"/community/adoptionReview\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">커뮤니티</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/community/adoptionReview\" class=\"dropdown-item\">입양후기</a>\n");
      out.write("              	<a href=\"/community/freeBoard\" class=\"dropdown-item\">자유게시판</a>\n");
      out.write("                <!-- <a href=\"#\" class=\"dropdown-item\">진행중인 캠페인</a> -->\n");
      out.write("                <a href=\"/community/usedItems\" class=\"dropdown-item\">중고거래게시판</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">중고거래</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">채팅목록</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래 후기</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("\n");
      out.write("            <li id=\"reservation\" class=\"nav-item dropdown\"><a href=\"/reservation/visit\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">방문예약</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/reservation/visit\" class=\"dropdown-item\">방문상담 예약</a>\n");
      out.write("                <a href=\"/reservation/volunteer\" class=\"dropdown-item\">봉사활동 예약</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            \n");
      out.write("            <li id=\"mall\" class=\"nav-item dropdown\"><a href=\"/anymoremall/product_list\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">애니모어 몰</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/anymoremall/product_list\" class=\"dropdown-item\">상품목록</a>\n");
      out.write("                <a href=\"/anymoremall/cart\" class=\"dropdown-item\">장바구니</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("	        </ul>\n");
      out.write("	      </div>\n");
      out.write("	    </div>\n");
      out.write("	  </nav>\n");
      out.write("	  \n");
      out.write("	  <!-- loader -->\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"../js/jquery.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\n");
      out.write("  <script src=\"../js/main.js\"></script>\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	.join_form{\r\n");
      out.write("		font-family: NanumSquareNeo;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.ftco-section .contactForm .label{\r\n");
      out.write("		font-size:15px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.join_form .btn{\r\n");
      out.write("		background-color:#AD8B73;\r\n");
      out.write("		color:white;\r\n");
      out.write("		margin-top:30px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.join_form .btn_2{\r\n");
      out.write("		margin-top:35px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.join_form .col-md-1{\r\n");
      out.write("		margin-top:50px;\r\n");
      out.write("		margin-left:10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.join_form .form-group{\r\n");
      out.write("		margin-bottom:50px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"ftco-section bg-light\">\r\n");
      out.write("	<div class=\"container join_form\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-md-6 text-center mb-5\">\r\n");
      out.write("				<h2 class=\"heading-section\">회원 가입</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-md-12\">\r\n");
      out.write("				<div class=\"wrapper\">\r\n");
      out.write("					<div class=\"row mb-5\">\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"dbox w-100 text-center\">\r\n");
      out.write("		        				<div class=\"icon d-flex align-items-center justify-content-center jicon1\">\r\n");
      out.write("		        					<img src=\"../images/file.png\">\r\n");
      out.write("		        				</div>\r\n");
      out.write("		        				<div class=\"text\">\r\n");
      out.write("			            			<p><span>약관 동의</span></p>\r\n");
      out.write("			          			</div>\r\n");
      out.write("		          			</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"dbox w-100 text-center\">\r\n");
      out.write("		        				<div class=\"icon d-flex align-items-center justify-content-center jicon2\">\r\n");
      out.write("		        					<img src=\"../images/write.png\">\r\n");
      out.write("		        				</div>\r\n");
      out.write("		        				<div class=\"text\">\r\n");
      out.write("			            			<p><span>정보 입력</span><hr style=\"border: solid 1px #AD8B73;\">\r\n");
      out.write("			          			</div>\r\n");
      out.write("		          			</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"dbox w-100 text-center\">\r\n");
      out.write("		        				<div class=\"icon d-flex align-items-center justify-content-center jicon3\">\r\n");
      out.write("		        					<img src=\"../images/checked.png\">\r\n");
      out.write("		        				</div>\r\n");
      out.write("				        		<div class=\"text\">\r\n");
      out.write("					            	<p><span>가입 완료</span>\r\n");
      out.write("					          	</div>\r\n");
      out.write("		         			 </div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"row no-gutters terms_content\">\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<div class=\"contact-wrap w-100 p-md-5 p-4\">\r\n");
      out.write("								<h3 class=\"mb-4\">정보 입력</h3>\r\n");
      out.write("								<form method=\"POST\" action=\"/join/join_complete\" id=\"joinform\" name=\"joinform\" class=\"joinform\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"name\">이름</label>\r\n");
      out.write("												<input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\" maxlength=\"10\" placeholder=\"이름을 입력하세요.\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-10\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"id\">아이디</label>\r\n");
      out.write("												<input type=\"text\" class=\"form-control\" name=\"id\" id=\"id\" placeholder=\"6 ~ 20 자리의 한글,영문,숫자  조합\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<input type=\"button\" class=\"btn id_check\" id=\"id_check\" value=\"중복 확인\" \r\n");
      out.write("												style=\"position:relative; top:6.5px; float:right;\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"birth\">생년월일</label>\r\n");
      out.write("												<input type=\"date\" class=\"form-control\" name=\"birth\" id=\"birth\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"email\">이메일</label>\r\n");
      out.write("												<input type=\"text\" class=\"form-control\" name=\"email\" id=\"email\" maxlength=\"50\" placeholder=\"이메일 주소를 입력해주세요.\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"password\">비밀번호</label>\r\n");
      out.write("												<input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" maxlength=\"20\" placeholder=\"8 ~ 20 자리의 영문,숫자,특수문자 조합\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"pass_check\">비밀번호 확인</label>\r\n");
      out.write("												<input type=\"password\" class=\"form-control\" name=\"pass_check\" id=\"pass_check\" maxlength=\"20\" placeholder=\"비밀번호를 한번 더 입력해주세요.\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"pass_question\">비밀번호 찾기 질문</label>\r\n");
      out.write("												<select name=\"pass_question\" id=\"pass_question\" style=\"width:100%; height:30px; font-family:NanumSquareNeo;\" >\r\n");
      out.write("													 <option value=\"\" selected>질문을 선택해주세요.</option>\r\n");
      out.write("													 <option value=\"1\">가장 좋아했던 동화책의 제목은 무엇입니까?</option>\r\n");
      out.write("													 <option value=\"2\">부모님이 처음 만난 도시는 어디입니까?</option>\r\n");
      out.write("													 <option value=\"3\">처음으로 가보았던 해변의 이름은 무엇입니까?</option>\r\n");
      out.write("													 <option value=\"4\">어렸을 적 가장 친했던 친구의 이름은 무엇입니까?</option>\r\n");
      out.write("													 <option value=\"5\">첫 반려동물의 이름은 무엇입니까?</option>\r\n");
      out.write("												</select>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"pass_answer\">비밀번호 찾기 답</label>\r\n");
      out.write("												<input type=\"text\" class=\"form-control\" name=\"pass_answer\" id=\"pass_answer\" maxlength=\"100\" placeholder=\"비밀번호 찾기 질문에 대한 답을 입력해주세요.\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"phone\">휴대폰 번호</label>\r\n");
      out.write("												<input type=\"text\" class=\"form-control\" name=\"phone\" id=\"phone\" maxlength=\"11\" placeholder=\"- 을 제외하고 입력해주세요.\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-10\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<label class=\"label\" for=\"address_1\">주소</label>\r\n");
      out.write("												<input type=\"text\" class=\"form-control\" name=\"address_1\" id=\"address_1\" placeholder=\"우편번호 검색을 진행해주세요.\" readonly>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<input type=\"button\" class=\"btn btn_2\" onclick=\"open_Postcode()\" value=\"우편번호 검색\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<input type=\"text\" class=\"form-control\" name=\"address_2\" id=\"address_2\" maxlength=\"100\" placeholder=\"상세 주소를 입력해주세요.\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<input type=\"hidden\" id=\"address\" name=\"address\" value=\"\">\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<a href=\"/join/join_terms\"><input type=\"button\" value=\"이전\" class=\"btn btn-primary\"></a>\r\n");
      out.write("												<input type=\"submit\" value=\"완료\" id=\"submit\" disabled=\"disabled\" class=\"btn btn-primary\" onclick=\"return validation()\">\r\n");
      out.write("												<div class=\"submitting\"></div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- 모달창 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"alertModal\" tabindex=\"-1\"\r\n");
      out.write("	aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("	<div class=\"modal-dialog modal-dialog-centered text-center\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("			<div class=\"modal-header\">\r\n");
      out.write("				<h5 class=\"modal-title\" id=\"alertModal\">알림</h5>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body\"></div>\r\n");
      out.write("			<div class=\"modal-footer\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("	//주소 합치기\r\n");
      out.write("	$(\"#address_1\").change(function(){\r\n");
      out.write("		address();	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#address_2\").change(function(){\r\n");
      out.write("		address();	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function address() {\r\n");
      out.write("		var address_1 = $(\"#address_1\").val();\r\n");
      out.write("		var address_2 = $(\"#address_2\").val();\r\n");
      out.write("		if(address_1 != \"\" && address_2 != \"\") {\r\n");
      out.write("			$(\"#address\").val(address_1 + \" \" + address_2);\r\n");
      out.write("		}\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	//전체 값 유효성 검사\r\n");
      out.write("	function validation(){\r\n");
      out.write("	 \r\n");
      out.write("		var name = document.getElementById(\"name\");\r\n");
      out.write("		var id = document.getElementById(\"id\");\r\n");
      out.write("		var birth = document.getElementById(\"birth\");\r\n");
      out.write("		var email = document.getElementById(\"email\");\r\n");
      out.write("		var password = document.getElementById(\"password\");\r\n");
      out.write("		var pass_check = document.getElementById(\"pass_check\");\r\n");
      out.write("		var pass_question = document.getElementById(\"pass_question\");\r\n");
      out.write("		var pass_answer = document.getElementById(\"pass_answer\");\r\n");
      out.write("		var phone = document.getElementById(\"phone\");\r\n");
      out.write("		var address_1 = document.getElementById(\"address_1\");\r\n");
      out.write("		var address_2 = document.getElementById(\"address_2\");\r\n");
      out.write("		var idChkVal = $(\"#id_check\").val();\r\n");
      out.write("		\r\n");
      out.write("		//비밀번호 영문자+숫자+특수조합(8~20자) 정규식\r\n");
      out.write("		var pass_varify = /^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,20}$/;\r\n");
      out.write("		\r\n");
      out.write("		//핸드폰 번호 정규식\r\n");
      out.write("		var phone_varify = /^[0-9]{10,11}$/;\r\n");
      out.write("		\r\n");
      out.write("		//이름 정규식\r\n");
      out.write("		var name_varify = /^[가-힣]{2,5}$/;\r\n");
      out.write("		\r\n");
      out.write("		//이메일 정규식\r\n");
      out.write("		var email_varify = /^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+$/;\r\n");
      out.write("		\r\n");
      out.write("		if(name.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"이름을 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			name.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//이름 유효성 검증\r\n");
      out.write("		if (!name_varify.test(name.value)) {\r\n");
      out.write("			$(\".modal-body\").html(\"이름을 확인해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("		 	name.focus();\r\n");
      out.write("		    return false;\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		if(id.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"아이디를 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			id.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(birth.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"생년월일을 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			birth.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(email.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"이메일 주소를 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			email.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//이메일 유효성 검증\r\n");
      out.write("		if (!email_varify.test(email.value)) {\r\n");
      out.write("			$(\".modal-body\").html(\"이메일 주소를 확인해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("		 	email.focus();\r\n");
      out.write("		    return false;\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		if(password.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			password.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		//비밀번호 조합 유효성 검증\r\n");
      out.write("		if (!pass_varify.test(password.value)) {\r\n");
      out.write("			$(\".modal-body\").html(\"비밀번호는 8 ~ 20 자리의 영문,숫자,특수문자를 조합하여 작성해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("		    password.focus();\r\n");
      out.write("		    return false;\r\n");
      out.write("		};\r\n");
      out.write("	\r\n");
      out.write("		if (pass_check.value !== password.value) {\r\n");
      out.write("			$(\".modal-body\").html(\"비밀번호가 일치하지 않습니다..\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("		    pass_check.focus();\r\n");
      out.write("		    return false;\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		if(pass_question.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"비밀번호 찾기 질문을 선택해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			pass_question.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(pass_answer.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"비밀번호 찾기 답을 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			pass_answer.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(phone.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"휴대폰 번호를 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			phone.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//휴대폰 번호 유효성 검증\r\n");
      out.write("		if (!phone_varify.test(phone.value)) {\r\n");
      out.write("			$(\".modal-body\").html(\"휴대폰 번호를 확인해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("		 	phone.focus();\r\n");
      out.write("		    return false;\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		if(address_1.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"우편번호 검색을 진행해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			address_1.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(address_2.value == \"\"){\r\n");
      out.write("			$(\".modal-body\").html(\"상세 주소를 입력해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			address_2.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//우편번호 검색\r\n");
      out.write("	function open_Postcode(){  \r\n");
      out.write("	  new daum.Postcode({ \r\n");
      out.write("	    oncomplete: function(data) { \r\n");
      out.write("	 \r\n");
      out.write("	       document.getElementById(\"address_1\").value = data.jibunAddress; \r\n");
      out.write("	  	} \r\n");
      out.write("	  }).open(); \r\n");
      out.write("	} \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//아이디 중복 체크\r\n");
      out.write("	$(\".id_check\").click(function(){\r\n");
      out.write(" \r\n");
      out.write("		var query = {id:$(\"#id\").val()};\r\n");
      out.write("		 \r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/idCheck\",\r\n");
      out.write("		  	type : \"post\",\r\n");
      out.write("		 	data : query,\r\n");
      out.write("		 	dataType:'json',\r\n");
      out.write("		  	success : function(data) {\r\n");
      out.write("			  	if(data == 1) {\r\n");
      out.write("			  		$(\".modal-body\").html(\"이미 사용 중인 아이디입니다.\");\r\n");
      out.write("					$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			  		$(\"#submit\").attr(\"disabled\", \"disabled\");\r\n");
      out.write("			   	} else {\r\n");
      out.write("			   		$(\".modal-body\").html(\"사용이 가능한 아이디입니다.\");\r\n");
      out.write("					$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			   		$(\"#submit\").removeAttr(\"disabled\");\r\n");
      out.write("			   	}\r\n");
      out.write("		  	}\r\n");
      out.write("		});  // ajax 끝\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"> \r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"footer\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Anymore</h2>\r\n");
      out.write("						<p>우리 미래 세대에게 진정한 가치 사회를 이어주고 동물들이 웃을 수 있는 사회가 되기 위해 애니모어가 최선의 노력을 하겠습니다. 애니모어에 지속적인 관심과 격려로 함께 해주세요.</p>\r\n");
      out.write("						<br/>\r\n");
      out.write("			<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.facebook.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Facebook\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://twitter.com/?lang=ko\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Twitter\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.instagram.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Instagram\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Have a Questions?</h2>\r\n");
      out.write("						<div class=\"block-23 mb-3\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><span class=\"icon fa fa-map\"></span><span class=\"text\">서울특별시 성동구 행당로 17길 1-77</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-phone\"></span><span class=\"text\">02-2292-6337<br>(평일 09:00~12:00, 13:00~18:00)</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-paper-plane\"></span><span class=\"text\">info@anymore.or.kr</span></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("					</div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">후원문의</h2>\r\n");
      out.write("						<p>후원금은 사지 않고 입양하는 문화를 만들어 가기 위한 활동에 사용됩니다.</p>\r\n");
      out.write("            <a href=\"/about/support\">바로가기</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row mt-5\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib.com</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/join/../includes/header.jsp(51,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 전 -->\n");
          out.write("					                <a href=\"/member/login\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Login</span></a>\n");
          out.write("					                <a href=\"/join/join_main\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> Join</span></a>\n");
          out.write("					                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/join/../includes/header.jsp(56,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 후 -->\n");
          out.write("					                ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("			                        ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/join/../includes/header.jsp(57,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 관리자 로그인 -->\n");
          out.write("			                          ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write(" 관리자님 께서 로그인 중입니다.&nbsp;\n");
          out.write("			                          <a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						               <a href=\"/staffMyPage/member_list\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						               <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("			                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/join/../includes/header.jsp(58,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/join/../includes/header.jsp(63,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'n'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 사용자 로그인 -->\n");
          out.write("			                        	");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write(" 님께서 로그인 중입니다.&nbsp;\n");
          out.write("						              	<a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						                <a href=\"/myPage/edit\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/join/../includes/header.jsp(64,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
