/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-02-08 03:13:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_005fterms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/join/../includes/footer.jsp", Long.valueOf(1675659477205L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673112267838L));
    _jspx_dependants.put("/WEB-INF/views/join/../includes/header.jsp", Long.valueOf(1675659477208L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <title>애니모어 유기동물 보호센터</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write(" \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/animate.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap-datepicker.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/flaticon.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\n");
      out.write("    <link href=\"https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/anymore.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://kit.fontawesome.com/c27a828741.css\" crossorigin=\"anonymous\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("  \n");
      out.write("  <div class=\"wrap\" >\n");
      out.write("			<div class=\"container\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("				   	<div class=\"col-md-4\">	\n");
      out.write("						<div class=\"social-media\">\n");
      out.write("				    		<p class=\"mb-0 d-flex\">\n");
      out.write("				    			<a href=\"https://www.facebook.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-facebook\"><i class=\"sr-only\">Facebook</i></span></a>\n");
      out.write("				    			<a href=\"https://twitter.com/?lang=ko\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-twitter\"><i class=\"sr-only\">Twitter</i></span></a>\n");
      out.write("				    			<a href=\"https://www.instagram.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-instagram\"><i class=\"sr-only\">Instagram</i></span></a>\n");
      out.write("				    		</p>\n");
      out.write("		        		</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("			          <div class=\"col-md-8 d-flex align-items-center justify-content-end\">\n");
      out.write("			            <div class=\"social-media\">\n");
      out.write("				              <p class=\"mb-0 phone pl-md-2\">\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				              </p>\n");
      out.write("			            </div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("		\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\n");
      out.write("	    <div class=\"container\" >\n");
      out.write("	    	<a class=\"navbar-brand\" href=\"/index\"><span class=\"flaticon-pawprint-1 mr-2\"></span>Anymore</a>\n");
      out.write("	      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("	        <span class=\"fa fa-bars\"></span> Menu\n");
      out.write("	      </button>\n");
      out.write("	      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\" style=\"font-family: 'NanumSquareNeo';\">\n");
      out.write("	        <ul class=\"navbar-nav ml-auto\">\n");
      out.write("	        	<li id=\"home\" class=\"nav-item active\"><a href=\"/index\" class=\"nav-link\">HOME</a></li>\n");
      out.write("            <li id=\"about\" class=\"nav-item dropdown\"><a href=\"/about/introduce\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">보호소 소개</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/about/introduce\" class=\"dropdown-item\">소개</a>\n");
      out.write("                <a href=\"/about/map\" class=\"dropdown-item\">찾아오시는 길</a>\n");
      out.write("                <a href=\"/about/support\" class=\"dropdown-item\">후원</a>\n");
      out.write("                <a href=\"/about/facility\" class=\"dropdown-item\">보호소 시설 안내</a>\n");
      out.write("              </div>\n");
      out.write("            <li id=\"adopt\" class=\"nav-item dropdown\"><a href=\"/adopt/procedure\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입양하기</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/adopt/procedure\" class=\"dropdown-item\">입양절차</a>\n");
      out.write("                <a href=\"/adopt/protectAnimal\" class=\"dropdown-item\">입양하기</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">실종신고</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾습니다</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾았습니다</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("<!-- 	        <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입소신청</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소신청</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소절차</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("            \n");
      out.write("	          <li id=\"community\" class=\"nav-item dropdown\"><a href=\"/community/adoptionReview\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">커뮤니티</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/community/adoptionReview\" class=\"dropdown-item\">입양후기</a>\n");
      out.write("              	<a href=\"/community/freeBoard\" class=\"dropdown-item\">자유게시판</a>\n");
      out.write("                <!-- <a href=\"#\" class=\"dropdown-item\">진행중인 캠페인</a> -->\n");
      out.write("                <a href=\"/community/usedItems\" class=\"dropdown-item\">중고거래게시판</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">중고거래</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">채팅목록</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래 후기</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("\n");
      out.write("            <li id=\"reservation\" class=\"nav-item dropdown\"><a href=\"/reservation/visit\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">방문예약</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/reservation/visit\" class=\"dropdown-item\">방문상담 예약</a>\n");
      out.write("                <a href=\"/reservation/volunteer\" class=\"dropdown-item\">봉사활동 예약</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            \n");
      out.write("            <li id=\"mall\" class=\"nav-item dropdown\"><a href=\"/anymoremall/product_list\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">애니모어 몰</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/anymoremall/product_list\" class=\"dropdown-item\">상품목록</a>\n");
      out.write("                <a href=\"/anymoremall/cart\" class=\"dropdown-item\">장바구니</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("	        </ul>\n");
      out.write("	      </div>\n");
      out.write("	    </div>\n");
      out.write("	  </nav>\n");
      out.write("	  \n");
      out.write("	  <!-- loader -->\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"../js/jquery.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\n");
      out.write("  <script src=\"../js/main.js\"></script>\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	.join_terms{\r\n");
      out.write("		font-family: NanumSquareNeo;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.ftco-section .contactForm .label{\r\n");
      out.write("		font-size:15px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.join_terms .form-group{\r\n");
      out.write("		margin-bottom:50px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"ftco-section bg-light\">\r\n");
      out.write("	<div class=\"container join_terms\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-md-6 text-center mb-5\">\r\n");
      out.write("				<h2 class=\"heading-section\">회원 가입</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-md-12\">\r\n");
      out.write("				<div class=\"wrapper\">\r\n");
      out.write("					<div class=\"row mb-5\">\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"dbox w-100 text-center\">\r\n");
      out.write("		        				<div class=\"icon d-flex align-items-center justify-content-center jicon1\">\r\n");
      out.write("		        					<img src=\"../images/file.png\">\r\n");
      out.write("		        				</div>\r\n");
      out.write("		        				<div class=\"text\">\r\n");
      out.write("			            			<p><span>약관 동의</span></p><hr style=\"border: solid 1px #AD8B73;\">\r\n");
      out.write("			          			</div>\r\n");
      out.write("		          			</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"dbox w-100 text-center\">\r\n");
      out.write("		        				<div class=\"icon d-flex align-items-center justify-content-center jicon2\">\r\n");
      out.write("		        					<img src=\"../images/write.png\">\r\n");
      out.write("		        				</div>\r\n");
      out.write("		        				<div class=\"text\">\r\n");
      out.write("			            			<p><span>정보 입력</span>\r\n");
      out.write("			          			</div>\r\n");
      out.write("		          			</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-4\">\r\n");
      out.write("							<div class=\"dbox w-100 text-center\">\r\n");
      out.write("		        				<div class=\"icon d-flex align-items-center justify-content-center jicon3\">\r\n");
      out.write("		        					<img src=\"../images/checked.png\">\r\n");
      out.write("		        				</div>\r\n");
      out.write("				        		<div class=\"text\">\r\n");
      out.write("					            	<p><span>가입 완료</span>\r\n");
      out.write("					          	</div>\r\n");
      out.write("		         			 </div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"row no-gutters terms_content\">\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<div class=\"contact-wrap w-100 p-md-5 p-4\">\r\n");
      out.write("								<h3 class=\"mb-4\">약관 동의</h3>\r\n");
      out.write("								<form method=\"POST\" action=\"/join/join_form\" id=\"terms\" name=\"terms\" class=\"terms\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<input type=\"checkbox\" id=\"terms_1_check\" name=\"terms_1_check\">\r\n");
      out.write("												<label class=\"label\" for=\"terms_1\">개인정보 수집 및 이용 동의</label>\r\n");
      out.write("												<textarea name=\"terms_1\" class=\"form-control\" id=\"terms_1\" cols=\"30\" rows=\"10\" readonly>\r\n");
      out.write("1. 개인정보의 수집항목 및 수집방법 \r\n");
      out.write("통계청 나라통계사이트에서는 기본적인 회원 서비스 제공을 위한 필수정보로 실명인증정보와 가입정보로 구분하여 다음의 정보를 수집하고 있습니다. 필수정보를 입력해주셔야 회원 서비스 이용이 가능합니다.\r\n");
      out.write("\r\n");
      out.write("  가. 수집하는 개인정보의 항목 \r\n");
      out.write("    * 수집하는 필수항목\r\n");
      out.write("      - 실명인증정보 : 이름, 휴대전화번호, 본인 인증 또는 I-PIN(개인식별번호), GPKI\r\n");
      out.write("      - 가입정보 : 아이디, 비밀번호, 성명, 이메일, 전화번호, 휴대전화번호, 기관명\r\n");
      out.write("    * 선택항목\r\n");
      out.write("      - 주소, 기관의 부서명\r\n");
      out.write("	\r\n");
      out.write("   [컴퓨터에 의해 자동으로 수집되는 정보]\r\n");
      out.write("   인터넷 서비스 이용과정에서 아래 개인정보 항목이 자동으로 생성되어 수집될 수 있습니다. \r\n");
      out.write("    - IP주소, 서비스 이용기록, 방문기록 등\r\n");
      out.write("	\r\n");
      out.write("  나. 개인정보 수집방법\r\n");
      out.write("      홈페이지 회원가입을 통한 수집 \r\n");
      out.write("\r\n");
      out.write("2. 개인정보의 수집/이용 목적 및 보유/이용 기간\r\n");
      out.write("통계청 나라통계사이트에서는 정보주체의 회원 가입일로부터 서비스를 제공하는 기간 동안에 한하여 통계청 나라통계사이트 서비스를 이용하기 위한 최소한의 개인정보를 보유 및 이용 하게 됩니다. 회원가입 등을 통해 개인정보의 수집·이용, 제공 등에 대해 동의하신 내용은 언제든지 철회하실 수 있습니다. 회원 탈퇴를 요청하거나 수집/이용목적을 달성하거나 보유/이용기간이 종료한 경우, 사업 폐지 등의 사유발생시 개인 정보를 지체 없이 파기합니다.\r\n");
      out.write("\r\n");
      out.write("  * 실명인증정보\r\n");
      out.write("    - 개인정보 수집항목 : 이름, 휴대폰 본인 인증 또는 I-PIN(개인식별번호), GPKI\r\n");
      out.write("    - 개인정보의 수집·이용목적   : 홈페이지 이용에 따른 본인 식별/인증절차에 이용\r\n");
      out.write("    - 개인정보의 보유 및 이용기간 : I-PIN / GPKI는 별도로 저장하지 않으며 실명인증용으로만 이용\r\n");
      out.write("\r\n");
      out.write("  * 가입정보\r\n");
      out.write("    - 개인정보 수집항목 : 아이디, 비밀번호, 성명, 이메일, 전화번호, 휴대전환번호, 기관명\r\n");
      out.write("    - 개인정보의 수집·이용목적 : 홈페이지 서비스 이용 및 회원관리, 불량회원의 부정 이용방지, 민원신청 및 처리 등\r\n");
      out.write("    - 개인정보의 보유 및 이용기간 : 2년 또는 회원탈퇴시\r\n");
      out.write("\r\n");
      out.write("정보주체는 개인정보의 수집·이용목적에 대한 동의를 거부할 수 있으며, 동의 거부시 통계청 나라통계사이트에 회원가입이 되지 않으며, 통계청 나라통계사이트에서 제공하는 서비스를 이용할 수 없습니다.\r\n");
      out.write("\r\n");
      out.write("3. 수집한 개인정보 제3자 제공\r\n");
      out.write("통계청 나라통계사이트에서는 정보주체의 동의, 법률의 특별한 규정 등 개인정보 보호법 제17조 및 제18조에 해당하는 경우에만 개인정보를 제3자에게 제공합니다.\r\n");
      out.write("		\r\n");
      out.write("4. 개인정보 처리업무 안내\r\n");
      out.write("통계청 나라통계사이트에서는 개인정보의 취급위탁은 하지 않고 있으며, 원활한 서비스 제공을 위해 아래의 기관을 통한 실명인증 및 공공 I-PIN, GPKI 인증을 하고 있습니다. \r\n");
      out.write("\r\n");
      out.write("  * 수탁업체\r\n");
      out.write("    - SCI서울신용평가정보(주)\r\n");
      out.write("      · 위탁업무 내용 : 실명확인\r\n");
      out.write("      · 개인정보 보유 및 이용 기간 : 신용평가 기관에서는 이미 보유하고 있는 개인정보이기 때문에 별도로 저장하지 않음\r\n");
      out.write("    - 행정자치부\r\n");
      out.write("      · 위탁업무 내용 : 공공 I-PIN, GPKI 인증\r\n");
      out.write("      · 개인정보 보유 및 이용 기간 : 행정자치부에서는 이미 보유하고 있는 개인정보이기 때문에 별도로 저장하지 않음\r\n");
      out.write("												</textarea>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<input type=\"checkbox\" id=\"terms_2_check\" name=\"terms_2_check\">\r\n");
      out.write("												<label class=\"label\" for=\"terms_2\">서비스 약관 동의</label>\r\n");
      out.write("												<textarea name=\"terms_2\" class=\"form-control\" id=\"terms_2\" cols=\"30\" rows=\"10\" readonly>\r\n");
      out.write("제 1 장 총칙\r\n");
      out.write("\r\n");
      out.write("제 1 조 (목적)\r\n");
      out.write("본 약관은 통계청이 운영하는 나라통계시스템 운영홈페이지(이하 \"당 사이트\")에서 제공하는 모든 서비스(이하 \"서비스\")의 이용조건 및 절차, 이용자와 당 사이트의 권리, 의무, 책임사항과 기타 필요한 사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\r\n");
      out.write("제 2 조 (약관의 효력과 변경)\r\n");
      out.write("① 당 사이트는 이용자가 본 약관 내용에 동의하는 것을 조건으로 이용자에게 서비스를 제공하며, 당 사이트의 서비스 제공 행위 및 이용자의 서비스 사용 행위에는 본 약관을 우선적으로 적용하겠습니다.\r\n");
      out.write("② 당 사이트는 본 약관을 사전 고지 없이 변경할 수 있으며, 변경된 약관은 당 사이트 내에 공지함으로써 이용자가 직접 확인하도록 할 것입니다. 이용자가 변경된 약관에 동의하지 아니하는 경우 본인의 회원등록을 취소(회원탈퇴)할 수 있으며, 계속 사용할 경우에는 약관 변경에 대한 암묵적 동의로 간주됩니다. 변경된 약관은 공지와 동시에 그 효력을 발휘합니다.\r\n");
      out.write("\r\n");
      out.write("제 3 조 (약관 외 준칙)\r\n");
      out.write("본 약관에 명시되지 않은 사항은 전기통신기본법, 전기통신사업법, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 및 기타 관련 법령의 규정에 의합니다.\r\n");
      out.write("\r\n");
      out.write("제 4 조 (용어의 정의)\r\n");
      out.write("① 본 약관에서 사용하는 용어의 정의는 다음과 같습니다.\r\n");
      out.write(" 1. 이용자 : 본 약관에 따라 당 사이트가 제공하는 서비스를 받는 자\r\n");
      out.write(" 2. 가 입 : 당 사이트가 제공하는 신청서 양식에 해당 정보를 기입하고, 본 약관에 동의하여 서비스 이용계약을 완료시키는 행위\r\n");
      out.write(" 3. 회 원 : 당 사이트에 필요한 개인 정보를 제공하여 회원 등록을 한 자로서, 당 사이트의 정보 및 서비스를 이용할 수 있는 자\r\n");
      out.write(" 4. 아이디 : 이용고객의 식별과 이용자가 서비스 이용을 위하여 이용자가 정한 문자와 숫자의 조합\r\n");
      out.write(" 5. 비밀번호 : 아이디에 대한 본인 여부를 확인하기 위하여 사용되는 문자, 숫자, 특수문자 등의 조합\r\n");
      out.write(" 6. 탈퇴 : 서비스 또는 회원이 이용계약을 종료하는 행위\r\n");
      out.write("② 본 약관에서 정의하지 않은 용어는 개별서비스에 대한 별도 약관 및 이용규정에서 정의합니다.\r\n");
      out.write("\r\n");
      out.write("제 2 장 서비스 제공 및 이용\r\n");
      out.write("\r\n");
      out.write("제 5 조 (이용 계약의 성립)\r\n");
      out.write("① 이용계약은 이용자가 온라인으로 당 사이트에서 제공하는 이용계약 신청서를 작성하여 가입을 완료하는 것으로 성립됩니다.\r\n");
      out.write("② 당 사이트는 다음 각 호에 해당하는 경우에 가입을 취소할 수 있습니다.\r\n");
      out.write(" 1. 다른 사람의 명의를 사용하여 신청하였을 때\r\n");
      out.write(" 2. 이용 계약 신청서의 내용을 허위로 기재하였거나 신청하였을 때\r\n");
      out.write(" 3. 사회의 안녕 질서 혹은 미풍양속을 저해할 목적으로 신청하였을 때\r\n");
      out.write(" 4. 다른 사람의 당 사이트 서비스 이용을 방해하거나 그 정보를 도용하는 등의 행위를 하였을 때\r\n");
      out.write(" 5. 당 사이트를 이용하여 법령과 본 약관이 금지하는 행위를 하는 경우\r\n");
      out.write(" 6. 기타 당 사이트가 정한 이용신청요건이 미비 되었을 때\r\n");
      out.write("③ 당 사이트는 다음 각 호에 해당하는 경우 그 사유가 소멸될 때까지 이용계약 성립을 유보할 수 있습니다.\r\n");
      out.write(" 1. 서비스 관련 제반 용량이 부족한 경우\r\n");
      out.write(" 2. 기술상 장애 사유가 있는 경우\r\n");
      out.write("④ 당 사이트가 제공하는 서비스는 자체 개발하거나 다른 기관과의 협의 등을 통해 제공하는 일체의 서비스를 말하는 것이며, 그 내용을 변경할 경우에는 이용자에게 공지한 후 변경하여 제공할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제 6 조 (회원정보 사용에 대한 동의)\r\n");
      out.write("① 회원의 개인정보는 공공기관의 개인정보보호법에 의해 보호되며 당 사이트의  개인정보처리방침이 적용됩니다.\r\n");
      out.write("② 당 사이트의 회원 정보는 다음과 같이 수집, 사용, 관리, 보호됩니다.\r\n");
      out.write(" 1. 개인정보의 수집 : 당 사이트는 회원 가입시 회원이 제공하는 정보를 수집합니다.\r\n");
      out.write(" 2. 개인정보의 사용 : 당 사이트는 서비스 제공과 관련해서 수집된 회원정보를 본인의 승낙 없이 제3자에게 누설, 배포하지 않습니다. 단, 전기통신기본법 등 법률의 규정에 의해 국가기관의 요구가 있는 경우, 범죄에 대한 수사상의 목적이 있거나 방송통신심의위원회의 요청이 있는 경우 또는 기타 관계법령에서 정한 절차에 따른 요청이 있는 경우, 회원이 당 사이트에 제공한 개인정보를 스스로 공개한 경우에는 그러하지 않습니다.\r\n");
      out.write(" 3. 개인정보의 관리 : 회원은 개인정보의 보호 및 관리를 위하여 서비스의 개인정보관리에서 수시로 회원의 개인정보를 수정/삭제할 수 있습니다. 수신되는 정보 중 불필요하다고 생각되는 부분도 변경/조정할 수 있습니다. 개인정보의 이용기간은 이용자가 가입을 완료하고 개인정보관리에서 회원가입을 탈퇴하는 시점이며 보호기간도 동일합니다.\r\n");
      out.write(" 4. 개인정보의 보호 : 회원의 개인정보는 오직 회원만이 열람/수정/삭제 할 수 있으며, 이는 전적으로 회원의 아이디와 비밀번호에 의해 관리되고 있습니다. 따라서 타인에게 본인의 아이디와 비밀번호를 알려주어서는 아니 되며, 작업 종료 시에는 반드시 로그아웃 해주시고, 웹 브라우저의 창을 닫아주시기 바랍니다(이는 타인과 컴퓨터를 공유하는 인터넷 카페나 도서관 같은 공공장소에서 컴퓨터를 사용하는 경우에 회원의 정보의 보호를 위하여 필요한 사항입니다.)\r\n");
      out.write("\r\n");
      out.write("제 7 조 (회원의 정보 보안)\r\n");
      out.write("① 가입 신청자가 당 사이트 서비스 가입 절차를 완료하는 순간부터 회원은 입력한 정보의 비밀을 유지할 책임이 있으며, 회원의 아이디와 비밀번호를 타인에게 제공하여 발생하는 모든 결과에 대한 책임은 회원 본인에게 있습니다.\r\n");
      out.write("② 아이디와 비밀번호에 관한 모든 관리의 책임은 회원에게 있으며, 회원의 아이디나 비밀번호가 부정하게 사용되었다는 사실을 발견한 경우에는 즉시 당 사이트에 신고하여야 합니다. 신고를 하지 않음으로 인한 모든 책임은 회원 본인에게 있습니다.\r\n");
      out.write("③ 회원은 당 사이트 서비스의 사용 종료 시마다 정확히 접속을 종료하도록 해야 하며, 정확히 종료하지 아니함으로써 제3자가 이용자 또는 회원에 관한 정보를 이용하게 되는 등의 결과로 인해 발생하는 손해 및 손실에 대하여 당 사이트는 책임을 부담하지 아니합니다.\r\n");
      out.write("\r\n");
      out.write("제 8 조 (서비스 이용시간)\r\n");
      out.write("① 서비스 이용시간은 당 사이트의 업무상 또는 기술상 특별한 지장이 없는 한 연중무휴, 1일 24시간을 원칙으로 합니다.\r\n");
      out.write("② 제1항의 이용시간은 정기점검 등의 필요로 인하여 당 사이트가 정한 날 또는 시간 및 예기치 않은 사건사고로 인한 시간은 예외로 합니다.\r\n");
      out.write("\r\n");
      out.write("제 9 조 (서비스의 중지 및 정보의 저장과 사용)\r\n");
      out.write("① 당 사이트 서비스에 보관되거나 전송된 메시지 및 기타 통신 메시지 등의 내용이 국가의 비상사태, 정전, 당 사이트의 관리 범위 외의 서비스 설비 장애 및 기타 불가항력에 의하여 보관되지 못하였거나 삭제된 경우, 전송되지 못한 경우 및 기타 통신 데이터의 손실이 있을 경우에 당 사이트는 관련 책임을 부담하지 아니합니다.\r\n");
      out.write("② 당 사이트가 정상적인 서비스 제공의 어려움으로 인하여 일시적으로 서비스를 중지하여야 할 경우에는 서비스 중지 1주일 전의 고지 후 서비스를 중지할 수 있으며, 이 기간 동안 이용자가 고지내용을 인지하지 못한 데 대하여 당 사이트는 책임을 부담하지 아니합니다. 부득이한 사정이 있을 경우 위 사전 고지기간은 감축되거나 생략될 수 있습니다. 또한 위 서비스 중지에 의하여 본 서비스에 보관되거나 전송된 메시지 및 기타 통신 메시지 등의 내용이 보관되지 못하였거나 삭제․전송되지 못한 경우 및 기타 통신 데이터의 손실이 있을 경우에 대하여도 당 사이트는 책임을 부담하지 아니합니다.\r\n");
      out.write("③ 당 사이트의 사정으로 서비스를 영구적으로 중단하여야 할 경우 제2항에 의거합니다. 다만, 이 경우 사전 고지기간은 1개월로 합니다.\r\n");
      out.write("④ 당 사이트는 사전 고지 후 서비스를 일시적으로 수정, 변경 및 중단할 수 있으며, 이에 대하여 이용자 또는 제3자에게 어떠한 책임도 부담하지 아니합니다.\r\n");
      out.write("⑤ 당 사이트는 이용자가 본 약관의 내용에 위배되는 행동을 한 경우, 임의로 서비스 사용을 제한 및 중지할 수 있습니다. 이 경우 당 사이트는 위 이용자의 접속을 금지할 수 있습니다.\r\n");
      out.write("⑥ 장기간 휴면 회원인 경우 안내 메일 또는 공지사항 발표 후 1주일간의 통지 기간을 거쳐 서비스 사용을 중지할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제 10 조 (서비스의 변경 및 해지)\r\n");
      out.write("① 당 사이트는 이용자가 서비스를 이용하여 얻은 자료로 인한 손해에 관하여 책임을 지지 않으며, 회원이 본 서비스에 게재한 정보, 자료, 사실의 신뢰도, 정확성 등 내용에 관하여는 책임을 지지 않습니다.\r\n");
      out.write("② 당 사이트는 서비스 이용과 관련하여 가입자에게 발생한 손해 중 가입자의 고의, 과실에 의한 손해에 대하여 책임을 부담하지 아니합니다.\r\n");
      out.write("③ 회원을 탈퇴하고자 하는 경우에는 당 사이트 로그인 후 회원탈퇴 절차에 따라 해지할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제 11 조 (정보 제공 및 홍보물 게재)\r\n");
      out.write("① 당 사이트는 서비스를 운영함에 있어서 각종 정보를 서비스에 게재하는 방법 등으로 회원에게 제공할 수 있습니다.\r\n");
      out.write("② 당 사이트는 서비스에 적절하다고 판단되거나 활용 가능성 있는 홍보물을 게재할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제 12 조 (게시물의 저작권)\r\n");
      out.write("① 이용자가 게시한 게시물의 내용에 대한 권리는 이용자에게 있습니다.\r\n");
      out.write("② 당 사이트는 게시된 내용을 사전 통지 없이 편집, 이동할 수 있는 권리를 보유하며, 다음의 경우 사전 통지 없이 삭제할 수 있습니다.\r\n");
      out.write(" 1. 본 이용약관에 위배되거나 상용 또는 불법, 음란, 저속하다고 판단되는 게시물을 게시한 경우\r\n");
      out.write(" 2. 다른 이용자 또는 제 3자를 비방하거나 중상모략으로 명예를 손상시키는 내용인 경우\r\n");
      out.write(" 3. 공공질서 및 미풍양속에 위반되는 내용인 경우\r\n");
      out.write(" 4. 범죄적 행위에 결부된다고 인정되는 내용일 경우\r\n");
      out.write(" 5. 제3자의 저작권 등 기타 권리를 침해하는 내용인 경우\r\n");
      out.write(" 6. 기타 관계 법령에 위배되는 경우\r\n");
      out.write("③ 이용자의 게시물이 타인의 저작권을 침해함으로써 발생하는 민․형사상의 책임은 전적으로 이용자가 부담하여야 합니다.\r\n");
      out.write("\r\n");
      out.write("제 13 조 (이용자의 행동규범 및 서비스 이용제한)\r\n");
      out.write("① 이용자가 제공하는 정보의 내용이 허위인 것으로 판명되거나, 그러하다고 의심할 만한 합리적인 사유가 발생할 경우 당 사이트는 이용자의 본 서비스 사용을 일부 또는 전부 중지할 수 있으며, 이로 인해 발생하는 불이익에 대해 책임을 부담하지 아니합니다.\r\n");
      out.write("② 이용자가 당 사이트 서비스를 통하여 게시, 전송, 입수하였거나 전자메일 기타 다른 수단에 의하여 게시, 전송 또는 입수한 모든 형태의 정보에 대하여는 이용자가 모든 책임을 부담하며 당 사이트는 어떠한 책임도 부담하지 아니합니다.\r\n");
      out.write("③ 당 사이트는 당 사이트가 제공한 서비스가 아닌 가입자 또는 기타 유관기관이 제공하는 서비스의 내용상의 정확성, 완전성 및 질에 대하여 보장하지 않습니다. 따라서 당 사이트는 이용자가 위 내용을 이용함으로 인하여 입게 된 모든 종류의 손실이나 손해에 대하여 책임을 부담하지 아니합니다.\r\n");
      out.write("④ 이용자는 본 서비스를 통하여 다음과 같은 행동을 하지 않는데 동의합니다.\r\n");
      out.write(" 1. 타인의 아이디와 비밀번호를 도용하는 행위\r\n");
      out.write(" 2. 저속, 음란, 모욕적, 위협적이거나 타인의 사생활을 침해할 수 있는 내용을 전송, 게시, 게재, 전자메일 또는 기타의 방법으로 전송하는 행위\r\n");
      out.write(" 3. 서비스를 통하여 전송된 내용의 출처를 위장하는 행위\r\n");
      out.write(" 4. 법률, 계약에 의하여 이용할 수 없는 내용을 게시, 게재, 전자메일 또는 기타의 방법으로 전송하는 행위\r\n");
      out.write(" 5. 타인의 특허, 상표, 영업비밀, 저작권, 기타 지적재산권을 침해하는 내용을 게시, 게재, 전자메일 또는 기타의 방법으로 전송하는 행위\r\n");
      out.write(" 6. 당 사이트의 승인을 받지 아니한 광고, 판촉물, 정크메일, 스팸, 행운의 편지, 피라미드 조직 기타 다른 형태의 권유를 게시, 게재, 전자메일 또는 기타의 방법으로 전송하는 행위\r\n");
      out.write(" 7. 다른 이용자의 개인정보를 수집 또는 저장하는 행위\r\n");
      out.write("⑤ 당 사이트는 회원이 본 약관을 위배했다고 판단되면 서비스와 관련된 모든 정보를 이용자의 동의 없이 삭제할 수 있습니다.\r\n");
      out.write("⑥ 제1항의 규정에 의하여 서비스의 제한을 받게 된 이용자가 위 조치에 대한 이의가 \r\n");
      out.write("있을 경우에는 이의신청을 할 수 있으나 서비스 제한 시 삭제된 이용자의 데이터에 대해서는 책임지지 아니합니다. \r\n");
      out.write("⑦ 당 사이트는 제6항의 규정에 의한 이의신청에 대하여 그 확인이 완료될 때까지 이용제한을 연기할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제 3 장 의무 및 책임\r\n");
      out.write("\r\n");
      out.write("제 14 조 (당 사이트의 의무)\r\n");
      out.write("① 당 사이트는 법령과 본 약관이 금지하거나 미풍양속에 반하는 행위를 하지 않으며, 지속적이고 안정적으로 서비스를 제공하기 위해 노력할 의무가 있습니다.\r\n");
      out.write("② 당 사이트는 회원의 개인 신상 정보를 본인의 승낙 없이 타인에게 누설, 배포하지 않습니다. 다만, 전기통신관련법령 등 관계법령에 의하여 관계 국가기관 등의 요구가 있는 경우에는 그러하지 아니합니다.\r\n");
      out.write("③ 당 사이트는 이용자가 안전하게 당 사이트 서비스를 이용할 수 있도록 이용자의 개인정보 (신용정보 포함) 보호를 위한 보안시스템을 갖추어야 합니다.\r\n");
      out.write("④ 당 사이트는 이용자의 귀책사유로 인한 서비스 이용 장애에 대하여 책임을 지지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제 15 조 (회원의 의무)\r\n");
      out.write("① 회원 가입시에 요구되는 정보는 정확하게 기입하여야 합니다. 또한 이미 제공된 회원에 대한 정보가 정확한 정보가 되도록 유지, 갱신하여야 하며, 회원은 자신의 아이디 및 비밀번호를 제3자에게 이용하게 해서는 안 됩니다.\r\n");
      out.write("② 회원은 당 사이트의 사전 승낙 없이 서비스를 이용하여 어떠한 영리행위도 할 수 없습니다.\r\n");
      out.write("③ 회원은 당 사이트 서비스를 이용하여 얻은 정보를 당 사이트의 사전승낙 없이 복사, 복제, 변경, 번역, 출판·방송 기타의 방법으로 사용하거나 이를 타인에게 제공할 수 없습니다.\r\n");
      out.write("④ 이용자는 당 사이트 서비스 이용과 관련하여 다음 각 호의 행위를 하여서는 안 됩니다.\r\n");
      out.write(" 1. 다른 회원의 아이디를 부정 사용하는 행위\r\n");
      out.write(" 2. 범죄행위를 목적으로 하거나 기타 범죄행위와 관련된 행위\r\n");
      out.write(" 3. 선량한 풍속, 기타 사회질서를 해하는 행위\r\n");
      out.write(" 4. 타인의 명예를 훼손하거나 모욕하는 행위\r\n");
      out.write(" 5. 타인의 지적재산권 등의 권리를 침해하는 행위\r\n");
      out.write(" 6. 해킹행위 또는 컴퓨터바이러스의 유포행위\r\n");
      out.write(" 7. 타인의 의사에 반하여 광고성 정보 등 일정한 내용을 지속적으로 전송하는 행위\r\n");
      out.write(" 8. 서비스의 안전적인 운영에 지장을 주거나 줄 우려가 있는 일체의 행위\r\n");
      out.write(" 9. 당 사이트에 게시된 정보의 변경\r\n");
      out.write("\r\n");
      out.write("제 4 장 기 타\r\n");
      out.write("\r\n");
      out.write("제 16 조 (당 사이트의 소유권)\r\n");
      out.write("① 당 사이트가 제공하는 서비스, 그에 필요한 소프트웨어, 이미지, 마크, 로고, 디자인, 서비스명칭, 정보 및 상표 등과 관련된 지적재산권 및 기타 권리는 당 사이트에 소유권이 있습니다.\r\n");
      out.write("② 이용자는 당 사이트가 명시적으로 승인한 경우를 제외하고는 전항의 소정의 각 재산에 대한 전부 또는 일부의 수정, 대여, 대출, 판매, 배포, 제작, 양도, 재라이센스, 담보권 설정 행위, 상업적 이용 행위를 할 수 없으며, 제3자로 하여금 이와 같은 행위를 하도록 허락할 수 없습니다.\r\n");
      out.write("\r\n");
      out.write("제 17 조 (양도금지)\r\n");
      out.write("회원이 서비스의 이용권한, 기타 이용계약 상 지위를 타인에게 양도, 증여할 수 없으며, 이를 담보로 제공할 수 없습니다.\r\n");
      out.write("\r\n");
      out.write("제 18 조 (손해배상)\r\n");
      out.write("당 사이트는 무료로 제공되는 서비스와 관련하여 회원에게 어떠한 손해가 발생하더라도 당 사이트가 고의로 행한 범죄행위를 제외하고 이에 대하여 책임을 부담하지 아니합니다.\r\n");
      out.write("\r\n");
      out.write("제 19 조 (면책조항)\r\n");
      out.write("① 당 사이트는 서비스에 표출된 어떠한 의견이나 정보에 대해 확신이나 대표할 의무가 없으며 회원이나 제3자에 의해 표출된 의견을 승인하거나 반대하거나 수정하지 않습니다. 당 사이트는 어떠한 경우라도 회원이 서비스에 담긴 정보에 의존해 얻은 이득이나 입은 손해에 대해 책임이 없습니다.\r\n");
      out.write("② 당 사이트는 회원간 또는 회원과 제3자간에 서비스를 매개로 하여 물품거래 혹은 금전적 거래 등과 관련하여 어떠한 책임도 부담하지 아니하고, 회원이 서비스의 이용과 관련하여 기대하는 이익에 관하여 책임을 부담하지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제 20 조 (관할법원)\r\n");
      out.write("본 서비스 이용과 관련하여 발생한 분쟁에 대해 소송이 제기될 경우 대전지방법원을 전속적 관할 법원으로 합니다.\r\n");
      out.write("\r\n");
      out.write("부 칙\r\n");
      out.write("(시행일) 본 약관은 2018년 8월 1일부터 시행됩니다. 개정된 약관의 적용일자 이전 이용자 또는 회원은 개정된 이용약관의 적용을 받습니다.\r\n");
      out.write("								\r\n");
      out.write("												</textarea>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-12\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<a href=\"/index\"><input type=\"button\" value=\"취소\" class=\"btn btn-primary\"></a>\r\n");
      out.write("												<input type=\"submit\" value=\"다음\" class=\"btn btn-primary\" onclick=\"return validation()\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- 모달창 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"alertModal\" tabindex=\"-1\"\r\n");
      out.write("	aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("	<div class=\"modal-dialog modal-dialog-centered text-center\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("			<div class=\"modal-header\">\r\n");
      out.write("				<h5 class=\"modal-title\" id=\"alertModal\">알림</h5>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body\"></div>\r\n");
      out.write("			<div class=\"modal-footer\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	//약관동의 유효성 체크\r\n");
      out.write("	function validation(){\r\n");
      out.write("	 \r\n");
      out.write("		var checkbox = document.getElementById(\"terms_1_check\");\r\n");
      out.write("		var checkbox2 = document.getElementById(\"terms_2_check\");\r\n");
      out.write("		\r\n");
      out.write("		if(!checkbox.checked){\r\n");
      out.write("			$(\".modal-body\").html(\"약관에 동의해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			checkbox.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(!checkbox2.checked){\r\n");
      out.write("			$(\".modal-body\").html(\"약관에 동의해주세요.\");\r\n");
      out.write("			$(\"#alertModal\").modal(\"show\");\r\n");
      out.write("			checkbox2.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"> \r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"footer\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Anymore</h2>\r\n");
      out.write("						<p>우리 미래 세대에게 진정한 가치 사회를 이어주고 동물들이 웃을 수 있는 사회가 되기 위해 애니모어가 최선의 노력을 하겠습니다. 애니모어에 지속적인 관심과 격려로 함께 해주세요.</p>\r\n");
      out.write("						<br/>\r\n");
      out.write("			<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.facebook.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Facebook\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://twitter.com/?lang=ko\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Twitter\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.instagram.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Instagram\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Have a Questions?</h2>\r\n");
      out.write("						<div class=\"block-23 mb-3\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><span class=\"icon fa fa-map\"></span><span class=\"text\">서울특별시 성동구 행당로 17길 1-77</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-phone\"></span><span class=\"text\">02-2292-6337<br>(평일 09:00~12:00, 13:00~18:00)</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-paper-plane\"></span><span class=\"text\">info@anymore.or.kr</span></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("					</div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">후원문의</h2>\r\n");
      out.write("						<p>후원금은 사지 않고 입양하는 문화를 만들어 가기 위한 활동에 사용됩니다.</p>\r\n");
      out.write("            <a href=\"/about/support\">바로가기</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row mt-5\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib.com</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/join/../includes/header.jsp(51,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 전 -->\n");
          out.write("					                <a href=\"/member/login\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Login</span></a>\n");
          out.write("					                <a href=\"/join/join_main\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> Join</span></a>\n");
          out.write("					                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/join/../includes/header.jsp(56,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 후 -->\n");
          out.write("					                ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("			                        ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/join/../includes/header.jsp(57,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 관리자 로그인 -->\n");
          out.write("			                          ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write(" 관리자님 께서 로그인 중입니다.&nbsp;\n");
          out.write("			                          <a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						               <a href=\"/staffMyPage/member_list\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						               <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("			                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/join/../includes/header.jsp(58,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/join/../includes/header.jsp(63,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'n'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 사용자 로그인 -->\n");
          out.write("			                        	");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write(" 님께서 로그인 중입니다.&nbsp;\n");
          out.write("						              	<a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						                <a href=\"/myPage/edit\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/join/../includes/header.jsp(64,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
