/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-02-06 04:58:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./includes/header.jsp", Long.valueOf(1675659477208L));
    _jspx_dependants.put("/WEB-INF/views/./includes/footer.jsp", Long.valueOf(1675659477205L));
    _jspx_dependants.put("jar:file:/C:/Swork/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/controller/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673112267838L));
    _jspx_dependants.put("/WEB-INF/views/./popup/popup.jsp", Long.valueOf(1675644091584L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <title>애니모어 유기동물 보호센터</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write(" \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/animate.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.carousel.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/owl.theme.default.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap-datepicker.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/jquery.timepicker.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/flaticon.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\n");
      out.write("    <link href=\"https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/anymore.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://kit.fontawesome.com/c27a828741.css\" crossorigin=\"anonymous\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("  \n");
      out.write("  <div class=\"wrap\" >\n");
      out.write("			<div class=\"container\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("				   	<div class=\"col-md-4\">	\n");
      out.write("						<div class=\"social-media\">\n");
      out.write("				    		<p class=\"mb-0 d-flex\">\n");
      out.write("				    			<a href=\"https://www.facebook.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-facebook\"><i class=\"sr-only\">Facebook</i></span></a>\n");
      out.write("				    			<a href=\"https://twitter.com/?lang=ko\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-twitter\"><i class=\"sr-only\">Twitter</i></span></a>\n");
      out.write("				    			<a href=\"https://www.instagram.com/\" class=\"d-flex align-items-center justify-content-center\"><span class=\"fa fa-instagram\"><i class=\"sr-only\">Instagram</i></span></a>\n");
      out.write("				    		</p>\n");
      out.write("		        		</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("			          <div class=\"col-md-8 d-flex align-items-center justify-content-end\">\n");
      out.write("			            <div class=\"social-media\">\n");
      out.write("				              <p class=\"mb-0 phone pl-md-2\">\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					              ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				              </p>\n");
      out.write("			            </div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("		\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\n");
      out.write("	    <div class=\"container\" >\n");
      out.write("	    	<a class=\"navbar-brand\" href=\"/index\"><span class=\"flaticon-pawprint-1 mr-2\"></span>Anymore</a>\n");
      out.write("	      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("	        <span class=\"fa fa-bars\"></span> Menu\n");
      out.write("	      </button>\n");
      out.write("	      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\" style=\"font-family: 'NanumSquareNeo';\">\n");
      out.write("	        <ul class=\"navbar-nav ml-auto\">\n");
      out.write("	        	<li id=\"home\" class=\"nav-item active\"><a href=\"/index\" class=\"nav-link\">HOME</a></li>\n");
      out.write("            <li id=\"about\" class=\"nav-item dropdown\"><a href=\"/about/introduce\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">보호소 소개</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/about/introduce\" class=\"dropdown-item\">소개</a>\n");
      out.write("                <a href=\"/about/map\" class=\"dropdown-item\">찾아오시는 길</a>\n");
      out.write("                <a href=\"/about/support\" class=\"dropdown-item\">후원</a>\n");
      out.write("                <a href=\"/about/facility\" class=\"dropdown-item\">보호소 시설 안내</a>\n");
      out.write("              </div>\n");
      out.write("            <li id=\"adopt\" class=\"nav-item dropdown\"><a href=\"/adopt/procedure\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입양하기</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/adopt/procedure\" class=\"dropdown-item\">입양절차</a>\n");
      out.write("                <a href=\"/adopt/protectAnimal\" class=\"dropdown-item\">입양하기</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">실종신고</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾습니다</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">실종동물 찾았습니다</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("<!-- 	        <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">입소신청</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소신청</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">입소절차</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("            \n");
      out.write("	          <li id=\"community\" class=\"nav-item dropdown\"><a href=\"/community/adoptionReview\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">커뮤니티</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/community/adoptionReview\" class=\"dropdown-item\">입양후기</a>\n");
      out.write("              	<a href=\"/community/freeBoard\" class=\"dropdown-item\">자유게시판</a>\n");
      out.write("                <!-- <a href=\"#\" class=\"dropdown-item\">진행중인 캠페인</a> -->\n");
      out.write("                <a href=\"/community/usedItems\" class=\"dropdown-item\">중고거래게시판</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("<!--             <li class=\"nav-item dropdown\"><a href=\"#\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">중고거래</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">채팅목록</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래 후기</a>\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">중고거래</a>\n");
      out.write("              </div>\n");
      out.write("            </li> -->\n");
      out.write("\n");
      out.write("            <li id=\"reservation\" class=\"nav-item dropdown\"><a href=\"/reservation/visit\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">방문예약</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/reservation/visit\" class=\"dropdown-item\">방문상담 예약</a>\n");
      out.write("                <a href=\"/reservation/volunteer\" class=\"dropdown-item\">봉사활동 예약</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            \n");
      out.write("            <li id=\"mall\" class=\"nav-item dropdown\"><a href=\"/anymoremall/product_list\" class=\"nav-link dropdown-toggle active\" data-bs-toggle=\"dropdown\">애니모어 몰</a>\n");
      out.write("              <div class=\"dropdown-menu border-light m-0\">\n");
      out.write("                <a href=\"/anymoremall/product_list\" class=\"dropdown-item\">상품목록</a>\n");
      out.write("                <a href=\"/anymoremall/cart\" class=\"dropdown-item\">장바구니</a>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("	        </ul>\n");
      out.write("	      </div>\n");
      out.write("	    </div>\n");
      out.write("	  </nav>\n");
      out.write("	  \n");
      out.write("	  <!-- loader -->\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\"../js/jquery.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\n");
      out.write("  <script src=\"../js/main.js\"></script>\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("<style>\r\n");
      out.write(".layerPopup{font-family: NanumSquareNeo;}\r\n");
      out.write(".layerPopup img{\r\n");
      out.write("margin-bottom : 20px;}\r\n");
      out.write(".layerPopup:before {display:block; content:\"\"; position:fixed; left:0; top:0; width:100%; height:100%; background:rgba(0,0,0,.5); z-index:9000}\r\n");
      out.write(".layerPopup .layerBox {    z-index:10000;   \r\n");
      out.write("position:fixed; right:50%; top:50%; transform:translate(-50%, -50%); padding:30px; background:#fff; border-radius:6px; }\r\n");
      out.write(".layerPopup .layerBox .title {margin-bottom:10px; padding-bottom:10px; font-weight:600; border-bottom:1px solid #d9d9d9;}\r\n");
      out.write(".layerPopup .layerBox .btnTodayHide {\r\n");
      out.write("font-size:14px; font-weight:600; color:black; \r\n");
      out.write("float: left;text-decoration:none;width: 150px; \r\n");
      out.write("height : 30px;line-height:30px;border:black solid 1px; text-align : center;text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(".layerPopup div{\r\n");
      out.write("	display : inline;\r\n");
      out.write("}\r\n");
      out.write(".layerPopup form{\r\n");
      out.write("	margin-top : 5px;\r\n");
      out.write("	font-size:16px; font-weight:600;\r\n");
      out.write("	weight: 100%;\r\n");
      out.write("	height : 30px;\r\n");
      out.write("	line-height:30px\r\n");
      out.write("}\r\n");
      out.write(".layerPopup #close {\r\n");
      out.write("font-size:16px; font-weight:600; width: 40px; height : 30px;color:black; float: right; line-height:30px; text-align : center;text-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write(".layerPopup a{\r\n");
      out.write("	text-decoration : none;\r\n");
      out.write("	color : black;width: 50px;height : 40px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("<!-- layer popup content -->\r\n");
      out.write("<div class=\"layerPopup\" id=\"layer_popup\" style=\"visibility: visible;\">\r\n");
      out.write("    <div class=\"layerBox\">\r\n");
      out.write("        <h4 class=\"title\">Anymore 공지사항</h4>\r\n");
      out.write("        <div class=\"cont\">\r\n");
      out.write("            <p>\r\n");
      out.write("            	<img src=\"../images/popup.jpg\" width=350 height=350 usemap=\"#popup\" alt=\"event page\">\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("          <form name=\"pop_form\">\r\n");
      out.write("        <div id=\"check\" ><input type=\"checkbox\" name=\"chkbox\" value=\"checkbox\" id='chkbox' >\r\n");
      out.write("        <label for=\"chkbox\">&nbsp;&nbsp;오늘 하루동안 보지 않기</label></div>\r\n");
      out.write("		<div id=\"close\" ><a href=\"javascript:closePop();\">닫기</a></div>    \r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	 //쿠키 설정\r\n");
      out.write("     function setCookie( name, value, expiredays ) {\r\n");
      out.write("         var todayDate = new Date();\r\n");
      out.write("         todayDate.setDate( todayDate.getDate() + expiredays ); \r\n");
      out.write("         document.cookie = name + \"=\" + escape( value ) + \"; path=/; expires=\" + todayDate.toUTCString() + \";\"\r\n");
      out.write("     }\r\n");
      out.write("	 \r\n");
      out.write("	 //오늘 하루동안 보지않기 체크하고 닫기 누를 시 설정한 쿠키 생성\r\n");
      out.write("     function closePop() {\r\n");
      out.write("         if ( document.pop_form.chkbox.checked ){\r\n");
      out.write("             setCookie( \"popupcookie\", \"done\" , 1 );\r\n");
      out.write("         }\r\n");
      out.write("         document.all['layer_popup'].style.visibility = \"hidden\";\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("    cookiedata = document.cookie; \r\n");
      out.write("    \r\n");
      out.write("    //생성된 쿠키의 기간이 만료 시 팝업 보이기\r\n");
      out.write("    if ( cookiedata.indexOf(\"popupcookie=done\") < 0 ){     \r\n");
      out.write("        document.all['layer_popup'].style.visibility = \"visible\";\r\n");
      out.write("    }\r\n");
      out.write("    else {\r\n");
      out.write("        document.all['layer_popup'].style.visibility = \"hidden\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<style>\r\n");
      out.write("	.milestone {\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"hero-wrap js-fullheight\" style=\"background-image: url('images/main4.jpg');\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters slider-text js-fullheight align-items-center justify-content-center\" data-scrollax-parent=\"true\">\r\n");
      out.write("          <div class=\"col-md-11 ftco-animate text-center\">\r\n");
      out.write("          	<h1 class=\"mb-4\">Adopt Animals, Adopt Family</h1>\r\n");
      out.write("            <h3 class=\"mb-4\" style=\"font-family: 'NanumSquareNeo';\">애니모어는 사지 않고 입양하는 문화를 만듭니다.</h3>\r\n");
      out.write("            <p><a href=\"/adopt/protectAnimal\" class=\"btn btn-primary mr-md-4 py-3 px-4\" style=\"font-family: 'NanumSquareNeo';\">입양하기<span class=\"ion-ios-arrow-forward\"></span></a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section bg-light ftco-no-pt ftco-intro\">\r\n");
      out.write("    	<div class=\"container\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("    		<div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 d-flex align-self-stretch px-4 ftco-animate milestone\" onclick=\"location.href='/hospital/animal_hospital'\">\r\n");
      out.write("            <div class=\"d-block services text-center\">\r\n");
      out.write("              <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("            		<!-- <span class=\"flaticon-blind\"></span> -->\r\n");
      out.write("                <img src=\"images/dog.png\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"heading\">동물병원 검색</h3>\r\n");
      out.write("                <p>가까운 동물병원을 검색해보세요</p>\r\n");
      out.write("                <p></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex align-self-stretch px-4 ftco-animate milestone\" onclick=\"location.href='/anymoremall/product_list'\">\r\n");
      out.write("            <div class=\"d-block services text-center\">\r\n");
      out.write("              <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("            		<!-- <span class=\"flaticon-dog-eating\"></span> -->\r\n");
      out.write("                <img src=\"images/dog-in-front-of-a-man.png\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"heading\">애니모어 몰</h3>\r\n");
      out.write("                <p>애니모어만의 상품을 구매하고 <br>아이들에게 힘을 보태주세요.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>    \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex align-self-stretch px-4 ftco-animate milestone\" onclick=\"location.href='/customerService/notice'\">\r\n");
      out.write("            <div class=\"d-block services text-center\">\r\n");
      out.write("              <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("            		<!-- <span class=\"flaticon-grooming\"></span> -->\r\n");
      out.write("                <img src=\"images/loud-speaker.png\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"heading\">공지사항</h3>\r\n");
      out.write("                <p>애니모어팀에서 소식을 알립니다.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-counter\" id=\"section-counter\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("    	<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 text-center\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"171\">0</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("              	<span>오늘 구조된 동물 수</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 text-center\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"341\">0</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("              	<span>입양 완료된 동물 수</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 text-center\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"219\">0</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("              	<span>보호 중인 동물 수</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section bg-light ftco-faqs\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("    	<div class=\"container\">\r\n");
      out.write("    		<div class=\"row\">\r\n");
      out.write("    			\r\n");
      out.write("    			<div class=\"col-lg-12\">\r\n");
      out.write("    				<div class=\"heading-section mb-5 mt-5 mt-lg-0 text-center\">\r\n");
      out.write("              <span><img src=\"images/hwaldong.png\"></span>\r\n");
      out.write("	            <h2 class=\"mb-3\">애니모어 활동</h2>\r\n");
      out.write("	            \r\n");
      out.write("    				</div>\r\n");
      out.write("    				<div id=\"accordion\" class=\"myaccordion w-100\" aria-multiselectable=\"true\">\r\n");
      out.write("						  <div class=\"card\">\r\n");
      out.write("						    <div class=\"card-header p-0\" id=\"headingOne\">\r\n");
      out.write("						      <h2 class=\"mb-0\">\r\n");
      out.write("						        <button href=\"#collapseOne\" class=\"d-flex py-3 px-4 align-items-center justify-content-between btn btn-link\" data-parent=\"#accordion\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n");
      out.write("						        	<p class=\"mb-0\">애니모어 X 마하그리드 캠페인</p>\r\n");
      out.write("						          <i>\r\n");
      out.write("						            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-search-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write("									  <path d=\"M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z\"/>\r\n");
      out.write("									  <path d=\"M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z\"/>\r\n");
      out.write("									</svg>\r\n");
      out.write("								  </i>\r\n");
      out.write("						        </button>\r\n");
      out.write("						      </h2>\r\n");
      out.write("						    </div>\r\n");
      out.write("						    <div class=\"collapse\" id=\"collapseOne\" role=\"tabpanel\" aria-labelledby=\"headingOne\">\r\n");
      out.write("						      <div class=\"card-body py-30 px-0\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("						      		<li style=\"list-style:none; text-align:left; display:inline-blick; margin-right: 40px;\" >애니모어와 패션 브랜드 마하그리드가 함께 하는 유기동물 입양 캠페인. 입양된 동물과 동물을 맞이하는 새로운 가족은 모두 유기동물 입양 문화에 긍정적인 영향을 미치는 ‘포지티브 인플루언서’라는 메시지를 담았습니다. 콜라보 컬렉션은 반팔 티셔츠, 반바지, 모자, 반려동물 의류, 이동 가방 등으로 구성되었으며, 제품 판매 수익금 일부는 유기동물을 위한 후원금으로 사용됩니다.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("						      	\r\n");
      out.write("						      </div>\r\n");
      out.write("						    </div>\r\n");
      out.write("						  </div>\r\n");
      out.write("\r\n");
      out.write("						  <div class=\"card\">\r\n");
      out.write("						    <div class=\"card-header p-0\" id=\"headingTwo\" role=\"tab\">\r\n");
      out.write("						      <h2 class=\"mb-0\">\r\n");
      out.write("						        <button href=\"#collapseTwo\" class=\"d-flex py-3 px-4 align-items-center justify-content-between btn btn-link\" data-parent=\"#accordion\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("						        	<p class=\"mb-0\">유기동물 입양자를 위한 ‘애니모어샵’ 오픈</p>\r\n");
      out.write("						          <i>\r\n");
      out.write("						            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-search-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write("									  <path d=\"M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z\"/>\r\n");
      out.write("									  <path d=\"M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z\"/>\r\n");
      out.write("									</svg>\r\n");
      out.write("								  </i>\r\n");
      out.write("						        </button>\r\n");
      out.write("						      </h2>\r\n");
      out.write("						    </div>\r\n");
      out.write("						    <div class=\"collapse\" id=\"collapseTwo\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
      out.write("						      <div class=\"card-body py-3 px-0\">\r\n");
      out.write("						      	<ul>\r\n");
      out.write("                      <li style=\"list-style:none; text-align:left; display:inline-blick; margin-right: 40px;\">애니모어샵은 유기동물 입양자들이 필요한 입양용품을 합리적인 가격에 제공함으로써 입양용품 선택에 도움을 주고 경제적인 부담을 덜어주기 위해 만들어졌습니다. 판매 수익금 일부를 가족을 기다리는 유기동물들에게 양질의 사료로 기부하는 등 유기동물 입양 활성화를 위한 선순환을 만들어갈 계획입니다.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("						      </div>\r\n");
      out.write("						    </div>\r\n");
      out.write("						  </div>\r\n");
      out.write("\r\n");
      out.write("						  <div class=\"card\">\r\n");
      out.write("						    <div class=\"card-header p-0\" id=\"headingThree\" role=\"tab\">\r\n");
      out.write("						      <h2 class=\"mb-0\">\r\n");
      out.write("						        <button href=\"#collapseThree\" class=\"d-flex py-3 px-4 align-items-center justify-content-between btn btn-link\" data-parent=\"#accordion\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("						        	<p class=\"mb-0\">지디아 지하철 입양홍보 캠페인</p>\r\n");
      out.write("						          <i>\r\n");
      out.write("						            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-search-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write("									  <path d=\"M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z\"/>\r\n");
      out.write("									  <path d=\"M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z\"/>\r\n");
      out.write("									</svg>\r\n");
      out.write("								  </i>\r\n");
      out.write("						        </button>\r\n");
      out.write("						      </h2>\r\n");
      out.write("						    </div>\r\n");
      out.write("						    <div class=\"collapse\" id=\"collapseThree\" role=\"tabpanel\" aria-labelledby=\"headingThree\">\r\n");
      out.write("						      <div class=\"card-body py-3 px-0\">\r\n");
      out.write("						      	<ul>\r\n");
      out.write("                      <li style=\"list-style:none; text-align:left; display:inline-blick; margin-right: 40px;\">유기동물 입양에 대한 사회적 인식개선과 올바른 입양문화를 형성하기 위해 지디아와 함께 유기견 입양 캠페인을 진행합니다. 지하철 1~4호선의 디지털 종합안내도에서 '나의 평생가족이 되어줄래?'라는 제목의 평생가족을 찾고 있는 유기동물들을 소개하는 배너 광고가 24시간 송출됩니다. 지하철을 이용하다 가족을 기다리는 유기동물을 만난다면, 큐알코드를 인식해보세요! 유기동물의 자세한 정보와, 가족을 찾고 있는 더 많은 친구들을 볼 수 있습니다.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("						      </div>\r\n");
      out.write("						    </div>\r\n");
      out.write("						  </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"card\">\r\n");
      out.write("						    <div class=\"card-header p-0\" id=\"headingFour\" role=\"tab\">\r\n");
      out.write("						      <h2 class=\"mb-0\">\r\n");
      out.write("						        <button href=\"#collapseFour\" class=\"d-flex py-3 px-4 align-items-center justify-content-between btn btn-link\" data-parent=\"#accordion\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("						        	<p class=\"mb-0\">애니모어 매거진 창간</p>\r\n");
      out.write("						          <i>\r\n");
      out.write("						            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-search-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write("									  <path d=\"M6.5 4.482c1.664-1.673 5.825 1.254 0 5.018-5.825-3.764-1.664-6.69 0-5.018Z\"/>\r\n");
      out.write("									  <path d=\"M13 6.5a6.471 6.471 0 0 1-1.258 3.844c.04.03.078.062.115.098l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1.007 1.007 0 0 1-.1-.115h.002A6.5 6.5 0 1 1 13 6.5ZM6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z\"/>\r\n");
      out.write("									</svg>\r\n");
      out.write("								  </i>\r\n");
      out.write("						        </button>\r\n");
      out.write("						      </h2>\r\n");
      out.write("						    </div>\r\n");
      out.write("						    <div class=\"collapse\" id=\"collapseFour\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
      out.write("						      <div class=\"card-body py-3 px-0\">\r\n");
      out.write("						      	<ul>\r\n");
      out.write("                      <li style=\"list-style:none; text-align:left; display:inline-blick; margin-right: 40px;\">유기동물 입양에 대한 전문적인 정보와 유기동물을 입양한 가족의 따뜻한 이야기를 담은 애니모어 매거진을 창간했습니다.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("						      </div>\r\n");
      out.write("						    </div>\r\n");
      out.write("						  </div>\r\n");
      out.write("  \r\n");
      out.write("						</div>\r\n");
      out.write("	        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section \" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center pb-5 mb-3\">\r\n");
      out.write("          <div class=\"col-md-7 heading-section text-center ftco-animate\">\r\n");
      out.write("            <span><img src=\"images/pet-care.png\"></span>\r\n");
      out.write("            <h2>애니모어 보호 동물</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row d-flex\">\r\n");
      out.write("          <div class=\"carousel-testimony owl-carousel ftco-owl\">\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <div class=\"d-flex ftco-animate\">\r\n");
      out.write("                <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("                  <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('images/any-dog1.jpg');\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"text p-4\">\r\n");
      out.write("                    <div class=\"meta mb-2\">\r\n");
      out.write("                      <div><a href=\"#\">2023.01.13</a></div>\r\n");
      out.write("                      <div><a href=\"#\">안락사 15일 전</a></div>\r\n");
      out.write("                      <div><a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment\"></span> 3</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"heading\"><a href=\"#\">우리 사랑스러운 모카를 소개합니다!\r\n");
      out.write("                      모카는 생후 4개월로 추정되는 수컷아가이구요.\r\n");
      out.write("                      현재 중성화는 안되어있지만 모든 접종은 마친 상태에요.\r\n");
      out.write("                      건강도 너무 너무 좋고, 흰색과 갈색이 믹스된 아주 매력적인 아이랍니다!</a></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <div class=\"d-flex ftco-animate\">\r\n");
      out.write("                <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("                  <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('images/any-dog2.jpg');\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"text p-4\">\r\n");
      out.write("                    <div class=\"meta mb-2\">\r\n");
      out.write("                      <div><a href=\"#\">2023.01.18</a></div>\r\n");
      out.write("                      <div><a href=\"#\">안락사 18일 전</a></div>\r\n");
      out.write("                      <div><a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment\"></span> 7</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"heading\"><a href=\"#\">소심하지만 착한 아기공쥬 \"아람이\"를 소개합니다!😍\r\n");
      out.write("                      우리 아람이는 사진보다 실물이 천만배는 더 귀염뽀짝하고 사랑스러운 아가에요!\r\n");
      out.write("                      사람을 너무 좋아하는 순둥이 아람이에게 사랑을 듬뿍 주시며 자신감을 가득 채워주실 평생가족을 찾습니다!\r\n");
      out.write("                    </a></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <div class=\"d-flex ftco-animate\">\r\n");
      out.write("                <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("                  <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('images/any-dog3.jpg');\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"text p-4\">\r\n");
      out.write("                    <div class=\"meta mb-2\">\r\n");
      out.write("                      <div><a href=\"#\">2023.01.31</a></div>\r\n");
      out.write("                      <div><a href=\"#\">안락사 20일 전</a></div>\r\n");
      out.write("                      <div><a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment\"></span> 5</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"heading\"><a href=\"#\">\r\n");
      out.write("                      ✔ 하우스(켄넬), 앉아, 목줄, 훈련 매우 완벽합니다.<br>\r\n");
      out.write("                      ✔ 기다려, 찬천히(먹는법), 엎드려, 훈련중이며 매우 적극적이고 습득력이 빠릅니다.<br>\r\n");
      out.write("                      ✔ 봉구는 애교가 많아요. 장난끼가 넘치며 사람과 노는것을 좋아합니다.<br>\r\n");
      out.write("                      ✔ 처음 대면하는 사람을 조금 경계를 하나 조심스레 접근하면 금방 친해집니다.</a></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <div class=\"d-flex ftco-animate\">\r\n");
      out.write("                <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("                  <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('images/any-cat1.jpg');\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"text p-4\">\r\n");
      out.write("                    <div class=\"meta mb-2\">\r\n");
      out.write("                      <div><a href=\"#\">2023.01.31</a></div>\r\n");
      out.write("                      <div><a href=\"#\">안락사 20일 전</a></div>\r\n");
      out.write("                      <div><a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment\"></span> 5</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"heading\"><a href=\"#\">\r\n");
      out.write("                      한 눈에 봐도 배가 불러있던 아띠는 보호소 입구 길냥이들 밥을 허겁지겁 먹고 있던 아이에요..😢 경계심이 심했지만, 간식으로 유인하니 할머님에게 다가와주었다고 해요.\r\n");
      out.write("                      아띠는 여전히 사람이 낯설어 손은 타지않지만, 따뜻한 가족의 사랑을 받으면 변하지않을까요? 아띠의 임보/입양 가족이 되어주세요.</a></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <div class=\"d-flex ftco-animate\">\r\n");
      out.write("                <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("                  <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('images//any-cat2.jpg');\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"text p-4\">\r\n");
      out.write("                    <div class=\"meta mb-2\">\r\n");
      out.write("                      <div><a href=\"#\">2023.01.31</a></div>\r\n");
      out.write("                      <div><a href=\"#\">안락사 20일 전</a></div>\r\n");
      out.write("                      <div><a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment\"></span> 5</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"heading\"><a href=\"#\">\r\n");
      out.write("                      중성화와 예방접종 완료한 수컷 코숏 치즈 태비 고양이입니다! 동물병원에서 나이는 한 살정도일거라고 말씀하셨어요! 몸무게는 3.3kg입니다. 치아, 귀, 피부 모두 깨끗한 고양이입니다. 그리고 무엇보다 동글동글 귀엽고 사랑스럽게 생겼답니다! 이름은 치몽이지만 가족이 되어주셔서 더 예쁘고 좋은 이름으로 불러주세요! </a></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <div class=\"d-flex ftco-animate\">\r\n");
      out.write("                <div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("                  <a href=\"blog-single.html\" class=\"block-20 rounded\" style=\"background-image: url('images/any-cat3.jpg');\">\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"text p-4\">\r\n");
      out.write("                    <div class=\"meta mb-2\">\r\n");
      out.write("                      <div><a href=\"#\">2023.01.31</a></div>\r\n");
      out.write("                      <div><a href=\"#\">안락사 20일 전</a></div>\r\n");
      out.write("                      <div><a href=\"#\" class=\"meta-chat\"><span class=\"fa fa-comment\"></span> 5</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"heading\"><a href=\"#\">\r\n");
      out.write("                      아파트 주차장 구석에서 경비원님의 제보로 어미도 없이 구조된 아깽이입니다.\r\n");
      out.write("                      성격은 순하고 기본검진 완료 진드기 없고 건강해요\r\n");
      out.write("                      입양전 충분한상담후 자택사진받고 입양계약서 작성하고 데려다드려요 \r\n");
      out.write("                      아깽이의 평생가족이 되어주세요 ❤</a></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section testimony-section\" style=\"background-image: url('images/main3.jpg'); font-family: 'NanumSquareNeo';\">\r\n");
      out.write("    	<div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center pb-5 mb-3\">\r\n");
      out.write("          <div class=\"col-md-7 heading-section text-center ftco-animate\">\r\n");
      out.write("            <img src=\"images/animal-care.png\">\r\n");
      out.write("            <h2>입양 후기</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row ftco-animate\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\"carousel-testimony owl-carousel ftco-owl\">\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                	<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">❤️사랑스러운 우리집 막내 “포비“ ❤️</p>\r\n");
      out.write("                    <p>진짜 애교쟁이에다가 말은 정말 안듣는 말썽꾸러기 포비예요 ㅎ 밖에서는 완전 겁쟁이에 품에 안기기 바쁘지만 집에서는 어찌나 땡강쟁이인지 이뻐 죽겠어요 ㅎ 벌써 포비를 데려온도 2달이 되었는데 그동안 많이 큰 것 같네요 너무 아쉽기도 하고 대견하기도 하고 ㅠ 막상 산책가면 신나서 날라다니는데 하네스 착용하면 대자로 엎드려서 시전도 해준답니다 ㅎㅎ 어딜가나 이쁨받는 저희집 막내 소개 및 자랑글이였습니다 항상 행복하게 해주께❤️ㅎㅎ</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    	<div class=\"user-img\" style=\"background-image: url(images/dog2.jpg)\"></div>\r\n");
      out.write("                    	<div class=\"pl-3\">\r\n");
      out.write("		                    <p class=\"name\">eun09</p>\r\n");
      out.write("		                    <span class=\"position\">2023.01.28</span>\r\n");
      out.write("		                  </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                	<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">새로운 친구</p>\r\n");
      out.write("                    <p class=\"mb-4\">어제 포인핸드를 보고 눈에뜨인 아이 그래서 보호소에 전화해서 확인하고 오늘 아침에 비오는 고속도로를 달려 만났네요. 눈도 크고 이쁜 아이 이름은 어제 저녁에 뽀미로 하자고 지었네요. 앞으로 항상 함께 할 울 뽀미 목욕시켜놓으니 더 이쁘네요. 예쁘고 건강하게 잘키울께요.</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    	<div class=\"user-img\" style=\"background-image: url(images/dog1.jpg)\"></div>\r\n");
      out.write("                    	<div class=\"pl-3\">\r\n");
      out.write("		                    <p class=\"name\">seinis</p>\r\n");
      out.write("		                    <span class=\"position\">2023.02.17</span>\r\n");
      out.write("		                  </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap py-4\">\r\n");
      out.write("                	<div class=\"icon d-flex align-items-center justify-content-center\"><span class=\"fa fa-quote-left\"></span></div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">보호소 출신 냥생 5개월차 콘부</p>\r\n");
      out.write("                    <p class=\"mb-4\">11월 말에 3개월된 콘부를 데려왔어요 보호소에서 사람 젤 잘 따른다고해서 데려왔고 처음봤을때는 괜찮았는데 입양일날 허피스때문에 눈이 많이 부어있는 상태였습니다. 지금은 결막이 협착된상태인데 병원에서 중성화때 정리하자 하셔서 그냥 놔두고있어요~ 그럼에도 잘먹고 잘뛰고 잘깨는 꼭 붙어자는 냥생 6개월차 콘부입니다 사람을 너무 좋아해서 혼자 사는 저로선 계속 붙어있을수 없어서 오빠 입양 한번 하려고요 요즘 외로워하는것 같더라고요</p>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    	<div class=\"user-img\" style=\"background-image: url(images/cat.jpg)\"></div>\r\n");
      out.write("                    	<div class=\"pl-3\">\r\n");
      out.write("		                    <p class=\"name\">joy912</p>\r\n");
      out.write("		                    <span class=\"position\">2023.01.04</span>\r\n");
      out.write("		                  </div>\r\n");
      out.write("	                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"> \r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"footer\" style=\"font-family: 'NanumSquareNeo';\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Anymore</h2>\r\n");
      out.write("						<p>우리 미래 세대에게 진정한 가치 사회를 이어주고 동물들이 웃을 수 있는 사회가 되기 위해 애니모어가 최선의 노력을 하겠습니다. 애니모어에 지속적인 관심과 격려로 함께 해주세요.</p>\r\n");
      out.write("						<br/>\r\n");
      out.write("			<ul class=\"ftco-footer-social p-0\">\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.facebook.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Facebook\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://twitter.com/?lang=ko\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Twitter\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("              <li class=\"ftco-animate\"><a href=\"https://www.instagram.com/\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Instagram\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">Have a Questions?</h2>\r\n");
      out.write("						<div class=\"block-23 mb-3\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><span class=\"icon fa fa-map\"></span><span class=\"text\">서울특별시 성동구 행당로 17길 1-77</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-phone\"></span><span class=\"text\">02-2292-6337<br>(평일 09:00~12:00, 13:00~18:00)</span></li>\r\n");
      out.write("                <li><span class=\"icon fa fa-paper-plane\"></span><span class=\"text\">info@anymore.or.kr</span></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("					</div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 mb-6 mb-md-0\">\r\n");
      out.write("						<h2 class=\"footer-heading\">후원문의</h2>\r\n");
      out.write("						<p>후원금은 사지 않고 입양하는 문화를 만들어 가기 위한 활동에 사용됩니다.</p>\r\n");
      out.write("            <a href=\"/about/support\">바로가기</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row mt-5\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p class=\"copyright\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib.com</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/./includes/header.jsp(51,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 전 -->\n");
          out.write("					                <a href=\"/member/login\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Login</span></a>\n");
          out.write("					                <a href=\"/join/join_main\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> Join</span></a>\n");
          out.write("					                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/./includes/header.jsp(56,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 로그인 후 -->\n");
          out.write("					                ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("			                        ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("					              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/./includes/header.jsp(57,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 관리자 로그인 -->\n");
          out.write("			                          ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write(" 관리자님 께서 로그인 중입니다.&nbsp;\n");
          out.write("			                          <a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						               <a href=\"/staffMyPage/member_list\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						               <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("			                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/./includes/header.jsp(58,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/./includes/header.jsp(63,27) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.staffs == 'n'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 사용자 로그인 -->\n");
          out.write("			                        	");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write(" 님께서 로그인 중입니다.&nbsp;\n");
          out.write("						              	<a href=\"/logout\" class=\"mr-2\"><span class=\"fa fa-user-o mr-1\"> Logout</span></a>\n");
          out.write("						                <a href=\"/myPage/edit\" class=\"mr-2\"><span class=\"fa fa-plus-square-o\"> mypage</span></a>\n");
          out.write("						                <a href=\"/customerService/notice\" class=\"mr-2\"><span class=\"fa fa-child\"> Customer service</span></a>\n");
          out.write("					                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/./includes/header.jsp(64,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
